### ISSUE TITLE
Type error in auto-generated absolute value function

### ISSUE THREAD

**Issue by vkuncak** [epfl-lara/stainless#1003]
Code such as https://github.com/epfl-lara/bolts/blob/7b764a1016b4b108ea49c5ea92b1409dd45c5023/data-structures/listmap/StrictlyOrderedLongListMap.scala when ran on master ( https://github.com/epfl-lara/stainless/commit/965b0ec485e62715003738e73605bd4dbb5da1da ) crashes in Inox with
```
inox.ast.TypeOps$TypeErrorException: Type error: if (x >= 0) {
  -x
} else {
  x
}, expected Long, 
found <untyped>

Typing explanation:
if (x >= 0) {
  -x
} else {
  x
} is of type <untyped>
  x >= 0 is of type <untyped>
    x is of type Long
    0 is of type Int
  -x is of type Long
    x is of type Long
  x is of type Long
	at inox.ast.TypeOps$TypeErrorException$.apply(TypeOps.scala:29)
	at inox.ast.TypeOps.typeCheck(TypeOps.scala:89)
	at inox.ast.TypeOps.typeCheck$(TypeOps.scala:85)
	at inox.ast.SimpleSymbols$SimpleSymbols.typeCheck(SimpleSymbols.scala:12)
	at inox.ast.Definitions$AbstractSymbols.ensureWellFormedFunction(Definitions.scala:228)
	at inox.ast.Definitions$AbstractSymbols.ensureWellFormedFunction$(Definitions.scala:227)
	at inox.ast.SimpleSymbols$SimpleSymbols.ensureWellFormedFunction(SimpleSymbols.scala:12)
	at inox.ast.Definitions$AbstractSymbols.$anonfun$ensureWellFormedSymbols$2(Definitions.scala:223)
	at inox.ast.Definitions$AbstractSymbols.$anonfun$ensureWellFormedSymbols$2$adapted(Definitions.scala:223)
	at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:985)
	at scala.collection.immutable.HashMap$HashMap1.foreach(HashMap.scala:399)
	at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:725)
	at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:725)
	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:984)
	at inox.ast.Definitions$AbstractSymbols.ensureWellFormedSymbols(Definitions.scala:223)
	at inox.ast.Definitions$AbstractSymbols.ensureWellFormedSymbols$(Definitions.scala:222)
	at inox.ast.SimpleSymbols$SimpleSymbols.ensureWellFormedSymbols(SimpleSymbols.scala:12)
	at inox.ast.Definitions$AbstractSymbols.$anonfun$inox$ast$Definitions$AbstractSymbols$$_tryWF$2(Definitions.scala:220)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.util.Try$.apply(Try.scala:213)
	at inox.ast.Definitions$AbstractSymbols.$anonfun$inox$ast$Definitions$AbstractSymbols$$_tryWF$1(Definitions.scala:220)
	at inox.utils.Lazy.get(Lazy.scala:13)
	at inox.ast.Definitions$AbstractSymbols.ensureWellFormed(Definitions.scala:219)
	at inox.ast.Definitions$AbstractSymbols.ensureWellFormed$(Definitions.scala:219)
	at inox.ast.SimpleSymbols$SimpleSymbols.ensureWellFormed(SimpleSymbols.scala:12)
	at inox.solvers.unrolling.AbstractUnrollingSolver.$anonfun$assertCnstr$2(UnrollingSolver.scala:167)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.util.Try$.apply(Try.scala:213)
	at inox.utils.TimerStorage.runAndGetTime(Timer.scala:93)
	at inox.utils.TimerStorage.run(Timer.scala:88)
	at inox.solvers.unrolling.AbstractUnrollingSolver.$anonfun$assertCnstr$1(UnrollingSolver.scala:166)
	at scala.util.Try$.apply(Try.scala:213)
	at inox.utils.TimerStorage.runAndGetTime(Timer.scala:93)
	at inox.utils.TimerStorage.run(Timer.scala:88)
	at inox.solvers.unrolling.AbstractUnrollingSolver.assertCnstr(UnrollingSolver.scala:165)
	at inox.solvers.unrolling.AbstractUnrollingSolver.assertCnstr$(UnrollingSolver.scala:165)
	at inox.solvers.SolverFactory$$anon$2.inox$tip$TipDebugger$$super$assertCnstr(SolverFactory.scala:125)
	at inox.tip.TipDebugger.assertCnstr(TipDebugger.scala:91)
	at inox.tip.TipDebugger.assertCnstr$(TipDebugger.scala:89)
	at inox.solvers.SolverFactory$$anon$2.assertCnstr(SolverFactory.scala:125)
	at inox.solvers.SolverFactory$$anon$2.assertCnstr(SolverFactory.scala:125)
	at inox.solvers.SimpleSolverAPI.solveVALID(SimpleSolverAPI.scala:21)
	at inox.solvers.SimpleSolverAPI.solveVALID$(SimpleSolverAPI.scala:18)
	at inox.solvers.SimpleSolverAPI$$anon$1.solveVALID(SimpleSolverAPI.scala:57)
	at stainless.termination.RelationProcessor.$anonfun$run$5(RelationProcessor.scala:50)
```

**Comment by jad-hamza** [comment]
Should be fixed now, thanks!
