### ISSUE TITLE
Error with type members: Cannot apply ClassFieldAccessor to type thiss.T

### ISSUE THREAD

**Issue by jad-hamza** [epfl-lara/stainless#1095]
Example `TypeMembers2.scala` which was in `extraction/valid` (was temporarily removed in #1088) crashes:

```scala
import stainless.annotation._

object TypeMembers2 {
  abstract class M {
    @mutable
    type T
    def c(t: T): Unit
  }

  case class A(var x: BigInt)

  case class F() extends M {
    type T = A

    def c(t: T) = {
      t.x += 2
    }
  }

  def test(x: F) = {
    val a = A(40)
    x.c(a)
    assert(a.x == 42)
  }
}
```

```scala
[ Debug  ] inox.package$FatalError: Cannot apply ClassFieldAccessor to type thiss.T
[ Debug  ]      at stainless.extraction.imperative.AntiAliasing.rec$1(AntiAliasing.scala:571)
[ Debug  ]      at stainless.extraction.imperative.AntiAliasing.stainless$extraction$imperative$AntiAliasing$$updatedTarget$1(AntiAliasing.scala:608)
[ Debug  ]      at stainless.extraction.imperative.AntiAliasing$transformer$1$.$anonfun$mapApplication$11(AntiAliasing.scala:244)
[ Debug  ]      at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
[ Debug  ]      at scala.collection.immutable.Set$Set1.foreach(Set.scala:141)
[ Debug  ]      at scala.collection.TraversableLike.map(TraversableLike.scala:286)
[ Debug  ]      at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
[ Debug  ]      at scala.collection.AbstractSet.scala$collection$SetLike$$super$map(Set.scala:53)
[ Debug  ]      at scala.collection.SetLike.map(SetLike.scala:105)
[...]
```

**Comment by vkuncak** [comment]
I confirm this still causes a crash, though it is not entirely clear to what extent we claim to be supporting type members.
