### ISSUE TITLE
RuntimeException with implicit class

### ISSUE THREAD

**Issue by OlivierBlanvillain** [epfl-lara/stainless#11]
I've tried adding a `forall` on `Set` using the following:

```scala
implicit class setForall[T](s: Set[T]) {
  def forall(p: T => Boolean): Boolean =
    stainless.lang.forall[T](e => s.contains(e) ==> p(e))
}
```

This leads to the following stack trace:

```
Exception in thread "main" java.lang.RuntimeException: Could not find 's' (s$0) within 
        at scala.sys.package$.error(package.scala:27)
        at inox.ast.Definitions$ADTConstructor.selectorID2Index(Definitions.scala:347)
        at inox.ast.Expressions$ADTSelector$$anonfun$selectorIndex$1.apply(Expressions.scala:269)
        at inox.ast.Expressions$ADTSelector$$anonfun$selectorIndex$1.apply(Expressions.scala:269)
        at scala.Option.map(Option.scala:146)
        at inox.ast.Expressions$ADTSelector.selectorIndex(Expressions.scala:269)
        at inox.solvers.z3.AbstractZ3Solver$class.rec$1(AbstractZ3Solver.scala:389)
        at inox.solvers.z3.AbstractZ3Solver$class.toZ3Formula(AbstractZ3Solver.scala:500)
        at inox.solvers.z3.NativeZ3Solver$underlying$.toZ3Formula(NativeZ3Solver.scala:23)
        at inox.solvers.z3.NativeZ3Solver$templates$.mkEncoder(NativeZ3Solver.scala:46)
        at inox.solvers.z3.NativeZ3Solver$templates$.mkEncoder(NativeZ3Solver.scala:32)
        at inox.solvers.unrolling.Templates$Template$$anonfun$15.apply(Templates.scala:542)
        at inox.solvers.unrolling.Templates$Template$$anonfun$15.apply(Templates.scala:542)
        at inox.solvers.unrolling.Templates$Template$$anonfun$16.apply(Templates.scala:559)
        at inox.solvers.unrolling.Templates$Template$$anonfun$16.apply(Templates.scala:546)
        at inox.ast.GenTreeOps$class.fold(GenTreeOps.scala:69)
        at inox.ast.Trees$$anon$1.fold(Trees.scala:32)
        at inox.ast.GenTreeOps$$anonfun$1.apply(GenTreeOps.scala:64)
        at inox.ast.GenTreeOps$$anonfun$1.apply(GenTreeOps.scala:64)
        at scala.collection.TraversableViewLike$Mapped$$anonfun$foreach$2.apply(TraversableViewLike.scala:169)
        at scala.collection.Iterator$class.foreach(Iterator.scala:893)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
        at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
        at scala.collection.SeqLike$$anon$2.foreach(SeqLike.scala:671)
        at scala.collection.TraversableViewLike$Mapped$class.foreach(TraversableViewLike.scala:168)
        at scala.collection.SeqViewLike$$anon$3.foreach(SeqViewLike.scala:197)
        at scala.collection.TraversableViewLike$FlatMapped$class.foreach(TraversableViewLike.scala:177)
        at scala.collection.SeqViewLike$$anon$4.foreach(SeqViewLike.scala:198)
        at scala.collection.TraversableOnce$class.toMap(TraversableOnce.scala:316)
        at scala.collection.SeqViewLike$AbstractTransformed.toMap(SeqViewLike.scala:37)
        at inox.solvers.unrolling.Templates$Template$$anonfun$16.apply(Templates.scala:547)
        at inox.solvers.unrolling.Templates$Template$$anonfun$16.apply(Templates.scala:546)
        at inox.ast.GenTreeOps$class.fold(GenTreeOps.scala:69)
        at inox.ast.Trees$$anon$1.fold(Trees.scala:32)
        at inox.solvers.unrolling.Templates$Template$.extractCalls(Templates.scala:570)
        at inox.solvers.unrolling.Templates$Template$$anonfun$34$$anonfun$apply$23.apply(Templates.scala:635)
        at inox.solvers.unrolling.Templates$Template$$anonfun$34$$anonfun$apply$23.apply(Templates.scala:634)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at inox.solvers.unrolling.Templates$Template$$anonfun$34.apply(Templates.scala:634)
        at inox.solvers.unrolling.Templates$Template$$anonfun$34.apply(Templates.scala:628)
        at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:733)
        at scala.collection.immutable.Map$Map3.foreach(Map.scala:161)
        at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:732)
        at inox.solvers.unrolling.Templates$Template$.encode(Templates.scala:628)
        at inox.solvers.unrolling.Templates$class.instantiateExpr(Templates.scala:816)
        at inox.solvers.z3.NativeZ3Solver$templates$.instantiateExpr(NativeZ3Solver.scala:32)
        at inox.solvers.unrolling.AbstractUnrollingSolver$class.assertCnstr(UnrollingSolver.scala:144)
        at inox.solvers.SolverFactory$$anonfun$getFromName$1$$anon$1.inox$tip$TipDebugger$$super$assertCnstr(SolverFactory.scala:115)
        at inox.tip.TipDebugger$class.assertCnstr(TipDebugger.scala:52)
        at inox.solvers.SolverFactory$$anonfun$getFromName$1$$anon$1.assertCnstr(SolverFactory.scala:115)
        at inox.solvers.SolverFactory$$anonfun$getFromName$1$$anon$1.assertCnstr(SolverFactory.scala:115)
        at stainless.verification.VerificationChecker$class.stainless$verification$VerificationChecker$$checkVC(VerificationChecker.scala:122)
        at stainless.verification.VerificationChecker$$anonfun$6.apply(VerificationChecker.scala:97)
        at stainless.verification.VerificationChecker$$anonfun$6.apply(VerificationChecker.scala:96)
        at scala.collection.TraversableLike$WithFilter$$anonfun$map$2.apply(TraversableLike.scala:683)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:682)
        at stainless.verification.VerificationChecker$class.checkVCs(VerificationChecker.scala:96)
        at stainless.verification.VerificationChecker$checker$2$.checkVCs(VerificationChecker.scala:185)
        at stainless.verification.VerificationChecker$class.verify(VerificationChecker.scala:54)
        at stainless.verification.VerificationChecker$checker$2$.verify(VerificationChecker.scala:185)
        at stainless.verification.VerificationChecker$.verify(VerificationChecker.scala:202)
        at stainless.verification.VerificationChecker$.verify(VerificationChecker.scala:206)
        at stainless.verification.VerificationComponent$.check(VerificationComponent.scala:84)
        at stainless.verification.VerificationComponent$.apply(VerificationComponent.scala:92)
        at stainless.verification.VerificationComponent$.apply(VerificationComponent.scala:9)
        at stainless.SimpleComponent$class.apply(Component.scala:59)
        at stainless.verification.VerificationComponent$.apply(VerificationComponent.scala:9)
        at stainless.MainHelpers$$anonfun$main$1.apply(MainHelpers.scala:76)
        at stainless.MainHelpers$$anonfun$main$1.apply(MainHelpers.scala:76)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at stainless.MainHelpers$class.main(MainHelpers.scala:76)
        at stainless.Main$.main(Main.scala:5)
        at stainless.Main.main(Main.scala)
```

**Comment by samarion** [comment]
If you declare `s` as a field of `setForall` (*i.e.* with `val`), your code will work.
Support for implicit classes is a bit of a dirty hack in Stainless. They're converted to case classes with the associated `equals`, `hashCode`, etc. methods, so they don't quite follow scala semantics...
I'm not sure we want to improve their usability for now.

**Comment by OlivierBlanvillain** [comment]
Thanks for looking into this, indeed a `val` seams to do the trick!
