### ISSUE TITLE
NoSuchElementException with nested foralls

### ISSUE THREAD

**Issue by OlivierBlanvillain** [epfl-lara/stainless#12]
While trying to prove properties on sorted lists, I used nested forall to express the fact that one list is smaller than the other:

```scala
def isSorted(list: List[BigInt]): Boolean = list match {
  case Cons(x, xs @ Cons(y, _)) => x <= y && isSorted(xs)
  case _ => true
}

def plusplus(l: List[BigInt], r: List[BigInt]) : List[BigInt] = {
  require(isSorted(l) && isSorted(r) && l.forall(e => r.forall(e.<=)))
  l ++ r
} ensuring(res => isSorted(res))
```

This leads to the stack trace below. Note that using `stainless.lang.forall` expression instead works as expected.

```
Exception in thread "main" java.util.NoSuchElementException: key not found: e
        at scala.collection.MapLike$class.default(MapLike.scala:228)
        at scala.collection.AbstractMap.default(Map.scala:59)
        at scala.collection.MapLike$class.apply(MapLike.scala:141)
        at scala.collection.AbstractMap.apply(Map.scala:59)
        at inox.solvers.unrolling.TemplateGenerator$$anonfun$6.apply(TemplateGenerator.scala:149)
        at inox.solvers.unrolling.TemplateGenerator$$anonfun$6.apply(TemplateGenerator.scala:149)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.immutable.Set$Set2.foreach(Set.scala:128)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
        at scala.collection.AbstractSet.scala$collection$SetLike$$super$map(Set.scala:47)
        at scala.collection.SetLike$class.map(SetLike.scala:92)
        at scala.collection.AbstractSet.map(Set.scala:47)
        at inox.solvers.unrolling.TemplateGenerator$class.mkExprStructure(TemplateGenerator.scala:149)
        at inox.solvers.z3.NativeZ3Solver$templates$.mkExprStructure(NativeZ3Solver.scala:32)
        at inox.solvers.unrolling.LambdaTemplates$LambdaTemplate$.apply(LambdaTemplates.scala:62)
        at inox.solvers.unrolling.TemplateGenerator$class.rec$1(TemplateGenerator.scala:350)
        at inox.solvers.unrolling.TemplateGenerator$$anonfun$rec$1$4.apply(TemplateGenerator.scala:390)
        at inox.solvers.unrolling.TemplateGenerator$$anonfun$rec$1$4.apply(TemplateGenerator.scala:390)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
        at scala.collection.immutable.List.map(List.scala:285)
        at inox.solvers.unrolling.TemplateGenerator$class.rec$1(TemplateGenerator.scala:390)
        at inox.solvers.unrolling.TemplateGenerator$$anonfun$rec$1$4.apply(TemplateGenerator.scala:390)
        at inox.solvers.unrolling.TemplateGenerator$$anonfun$rec$1$4.apply(TemplateGenerator.scala:390)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
        at scala.collection.immutable.List.map(List.scala:285)
        at inox.solvers.unrolling.TemplateGenerator$class.rec$1(TemplateGenerator.scala:390)
        at inox.solvers.unrolling.TemplateGenerator$class.mkExprClauses(TemplateGenerator.scala:393)
        at inox.solvers.z3.NativeZ3Solver$templates$.mkExprClauses(NativeZ3Solver.scala:32)
        at inox.solvers.unrolling.LambdaTemplates$LambdaTemplate$$anonfun$3.apply(LambdaTemplates.scala:71)
        at inox.solvers.unrolling.LambdaTemplates$LambdaTemplate$$anonfun$3.apply(LambdaTemplates.scala:70)
        at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124)
        at scala.collection.immutable.List.foldLeft(List.scala:84)
        at inox.solvers.unrolling.LambdaTemplates$LambdaTemplate$.apply(LambdaTemplates.scala:70)
        at inox.solvers.unrolling.TemplateGenerator$class.rec$1(TemplateGenerator.scala:350)
        at inox.solvers.unrolling.TemplateGenerator$$anonfun$rec$1$4.apply(TemplateGenerator.scala:390)
        at inox.solvers.unrolling.TemplateGenerator$$anonfun$rec$1$4.apply(TemplateGenerator.scala:390)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
        at scala.collection.immutable.List.map(List.scala:285)
        at inox.solvers.unrolling.TemplateGenerator$class.rec$1(TemplateGenerator.scala:390)
        at inox.solvers.unrolling.TemplateGenerator$$anonfun$rec$1$4.apply(TemplateGenerator.scala:390)
        at inox.solvers.unrolling.TemplateGenerator$$anonfun$rec$1$4.apply(TemplateGenerator.scala:390)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
        at scala.collection.immutable.List.map(List.scala:285)
        at inox.solvers.unrolling.TemplateGenerator$class.rec$1(TemplateGenerator.scala:390)
        at inox.solvers.unrolling.TemplateGenerator$class.recAnd$1(TemplateGenerator.scala:263)
        at inox.solvers.unrolling.TemplateGenerator$class.rec$1(TemplateGenerator.scala:277)
        at inox.solvers.unrolling.TemplateGenerator$class.mkExprClauses(TemplateGenerator.scala:393)
        at inox.solvers.z3.NativeZ3Solver$templates$.mkExprClauses(NativeZ3Solver.scala:32)
        at inox.solvers.unrolling.TemplateGenerator$class.mkClauses(TemplateGenerator.scala:67)
        at inox.solvers.z3.NativeZ3Solver$templates$.mkClauses(NativeZ3Solver.scala:32)
        at inox.solvers.unrolling.Templates$class.instantiateExpr(Templates.scala:813)
        at inox.solvers.z3.NativeZ3Solver$templates$.instantiateExpr(NativeZ3Solver.scala:32)
        at inox.solvers.unrolling.AbstractUnrollingSolver$class.assertCnstr(UnrollingSolver.scala:144)
        at inox.solvers.SolverFactory$$anonfun$getFromName$1$$anon$1.inox$tip$TipDebugger$$super$assertCnstr(SolverFactory.scala:115)
        at inox.tip.TipDebugger$class.assertCnstr(TipDebugger.scala:52)
        at inox.solvers.SolverFactory$$anonfun$getFromName$1$$anon$1.assertCnstr(SolverFactory.scala:115)
        at inox.solvers.SolverFactory$$anonfun$getFromName$1$$anon$1.assertCnstr(SolverFactory.scala:115)
        at stainless.verification.VerificationChecker$class.stainless$verification$VerificationChecker$$checkVC(VerificationChecker.scala:122)
        at stainless.verification.VerificationChecker$$anonfun$6.apply(VerificationChecker.scala:97)
        at stainless.verification.VerificationChecker$$anonfun$6.apply(VerificationChecker.scala:96)
        at scala.collection.TraversableLike$WithFilter$$anonfun$map$2.apply(TraversableLike.scala:683)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:682)
        at stainless.verification.VerificationChecker$class.checkVCs(VerificationChecker.scala:96)
        at stainless.verification.VerificationChecker$checker$2$.checkVCs(VerificationChecker.scala:185)
        at stainless.verification.VerificationChecker$class.verify(VerificationChecker.scala:54)
        at stainless.verification.VerificationChecker$checker$2$.verify(VerificationChecker.scala:185)
        at stainless.verification.VerificationChecker$.verify(VerificationChecker.scala:202)
        at stainless.verification.VerificationChecker$.verify(VerificationChecker.scala:206)
        at stainless.verification.VerificationComponent$.check(VerificationComponent.scala:84)
        at stainless.verification.VerificationComponent$.apply(VerificationComponent.scala:92)
        at stainless.verification.VerificationComponent$.apply(VerificationComponent.scala:9)
        at stainless.SimpleComponent$class.apply(Component.scala:59)
        at stainless.verification.VerificationComponent$.apply(VerificationComponent.scala:9)
        at stainless.MainHelpers$$anonfun$main$1.apply(MainHelpers.scala:76)
        at stainless.MainHelpers$$anonfun$main$1.apply(MainHelpers.scala:76)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at stainless.MainHelpers$class.main(MainHelpers.scala:76)
        at stainless.Main$.main(Main.scala:5)
        at stainless.Main.main(Main.scala)
```

**Comment by samarion** [comment]
Thanks for reporting, I fixed the bug in Inox with https://github.com/epfl-lara/inox/commit/4b032e6104254ab0cbe8d33df805d3117fcb4557.
