### ISSUE TITLE
Crash in dotty front end with Georg's aliasing example

### ISSUE THREAD

**Issue by vkuncak** [epfl-lara/stainless#1262]
This example is rejected cleanly with stainless-scalac but crashes stainless-dotty. Why?
```scala
import stainless.annotation.pure
case class Box(var length: Int)
object Foo {
  def makeBox(): Box = Box(0)

  @pure def f(b: Box): Unit = {
    val c =          
      if (true) b    
      else makeBox() 
    c.length = 1     
  }

  def mutate(b: Box): Unit = { b.length = 123; }

  def g(b1: Box, b2: Box): Unit = {
    val c = if (true) b1 else b2
    mutate(c)
  }

  def h(b1: Box, b2: Box): Unit = {
    val c = if (true) b1 else b2
    val d = c // Interacts with Let handling `computeExprEffects`
    mutate(d)
  }
}
```
Stack trace:
```
java.lang.AssertionError: assertion failed
	at scala.runtime.Scala3RunTime$.assertFailed(Scala3RunTime.scala:11)
	at stainless.extraction.imperative.AntiAliasing$TransformerImpl$1.transform(AntiAliasing.scala:509)
	at stainless.extraction.imperative.AntiAliasing.makeSideEffectsExplicit$1(AntiAliasing.scala:730)
	at stainless.extraction.imperative.AntiAliasing.$anonfun$7(AntiAliasing.scala:134)
	at scala.Option.map(Option.scala:242)
	at stainless.extraction.imperative.AntiAliasing.stainless$extraction$imperative$AntiAliasing$$_$updateFunction$1(AntiAliasing.scala:142)
	at stainless.extraction.imperative.AntiAliasing.extractFunction(AntiAliasing.scala:1293)
	at stainless.extraction.imperative.AntiAliasing.extractFunction(AntiAliasing.scala:85)
	at stainless.extraction.CachingPhase.$anonfun$3$$anonfun$1(ExtractionPipeline.scala:102)
	at stainless.extraction.utils.ConcurrentCache.cached(ConcurrentCaches.scala:26)
	at stainless.extraction.ExtractionCaches$ExtractionCache.cached(ExtractionCaches.scala:165)
	at stainless.extraction.CachingPhase.$anonfun$1(ExtractionPipeline.scala:102)
	at scala.collection.Iterator$$anon$9.next(Iterator.scala:575)
	at scala.collection.immutable.List.prependedAll(List.scala:156)
	at scala.collection.immutable.List$.from(List.scala:684)
	at scala.collection.immutable.List$.from(List.scala:681)
	at scala.collection.IterableFactory$Delegate.from(Factory.scala:288)
	at scala.collection.immutable.Iterable$.from(Iterable.scala:35)
	at scala.collection.immutable.Iterable$.from(Iterable.scala:32)
	at scala.collection.IterableFactory$Delegate.from(Factory.scala:288)
	at scala.collection.IterableOps.map(Iterable.scala:671)
	at scala.collection.IterableOps.map$(Iterable.scala:671)
	at scala.collection.AbstractIterable.map(Iterable.scala:919)
	at stainless.extraction.CachingPhase.extractSymbols(ExtractionPipeline.scala:102)
	at stainless.extraction.CachingPhase.extractSymbols$(ExtractionPipeline.scala:82)
	at stainless.extraction.imperative.AntiAliasing.stainless$extraction$oo$CachingPhase$$super$extractSymbols(AntiAliasing.scala:11)
	at stainless.extraction.imperative.AntiAliasing.stainless$extraction$oo$CachingPhase$$super$extractSymbols(AntiAliasing.scala:11)
	at stainless.extraction.oo.CachingPhase.extractSymbols(ExtractionPipeline.scala:28)
	at stainless.extraction.oo.CachingPhase.extractSymbols$(ExtractionPipeline.scala:13)
	at stainless.extraction.imperative.AntiAliasing.extractSymbols(AntiAliasing.scala:11)
	at stainless.extraction.imperative.AntiAliasing.extractSymbols(AntiAliasing.scala:11)
	at stainless.extraction.CachingPhase.extract(ExtractionPipeline.scala:97)
	at stainless.extraction.CachingPhase.extract$(ExtractionPipeline.scala:82)
	at stainless.extraction.imperative.AntiAliasing.extract(AntiAliasing.scala:11)
	at stainless.extraction.utils.DebugPipeline.extract$$anonfun$2$$anonfun$1(DebugPipeline.scala:136)
	at scala.util.Try$.apply(Try.scala:210)
	at inox.utils.TimerStorage.runAndGetTime(Timer.scala:93)
	at inox.utils.TimerStorage.run(Timer.scala:88)
	at stainless.extraction.utils.DebugPipeline.extract$$anonfun$1(DebugPipeline.scala:136)
	at stainless.extraction.utils.DebugSymbols.debug(DebugPipeline.scala:64)
	at stainless.extraction.utils.DebugSymbols.debug$(DebugPipeline.scala:29)
	at stainless.extraction.utils.DebugPipeline.debug(DebugPipeline.scala:124)
	at stainless.extraction.utils.DebugPipeline.extract(DebugPipeline.scala:137)
	at stainless.extraction.ExtractionPipeline$AndThenImpl$1.extract(ExtractionPipeline.scala:30)
	...
	at stainless.extraction.ExtractionPipeline$AndThenImpl$1.extract(ExtractionPipeline.scala:30)
	at stainless.ComponentRun.extract(Component.scala:87)
	at stainless.ComponentRun.extract$(Component.scala:47)
	at stainless.verification.VerificationRun.extract(VerificationComponent.scala:53)
	at stainless.ComponentRun.apply(Component.scala:97)
	at stainless.ComponentRun.apply$(Component.scala:47)
	at stainless.verification.VerificationRun.apply(VerificationComponent.scala:53)
	at stainless.frontend.SplitCallBack.$anonfun$8(SplitCallBack.scala:196)
	at scala.collection.immutable.List.map(List.scala:246)
	at scala.collection.immutable.List.map(List.scala:79)
	at stainless.frontend.SplitCallBack.processFunctionsSymbols(SplitCallBack.scala:198)
	at stainless.frontend.SplitCallBack.$anonfun$7(SplitCallBack.scala:170)
	at stainless.extraction.utils.ConcurrentCache.getOrElseUpdate(ConcurrentCaches.scala:15)
	at stainless.frontend.SplitCallBack.processFunctions(SplitCallBack.scala:170)
	at stainless.frontend.SplitCallBack.processSymbols(SplitCallBack.scala:156)
	at stainless.frontend.SplitCallBack.endExtractions(SplitCallBack.scala:78)
	at stainless.frontend.ThreadedFrontend$$anon$1.run(ThreadedFrontend.scala:34)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by mario-bucev** [comment]
The `scalac` frontend eliminates dead branches for us (but not the `dotty` one, at least not at the stage where Stainless is injected).
Due to an overzealous sanity check, an assertion is triggered (which I'd still like to keep...)
