### ISSUE TITLE
`NoSuchElementException` in interaction between lambdas and "auto-tupling"

### ISSUE THREAD

**Issue by Ef55** [epfl-lara/stainless#1302]
The following snippet compiles correctly in Scala 3.0.2, but crashes stainless.
```scala
import stainless.collection.*

object Test {
  def f(l: List[(BigInt, BigInt)]): Unit = {
    val _ = l.map(_._1).map( (x) => x )     // Works fine
    val _ = l.map(_._2).map( (y) => y )     // Works fine
    val _ = l.map{ case (x, y) => (x, y) }  // Works fine
    val _ = l.map( (x, y) => (x, y) )       // java.util.NoSuchElementException: key not found: def _$x: BigInt = x$1._1
    ()
  }
}
```

<details>
<summary>stainless-stack-trace.txt</summary>
<code>
java.util.NoSuchElementException: key not found: def _$x: BigInt = x$1._1
	at scala.collection.immutable.BitmapIndexedMapNode.apply(HashMap.scala:635)
	at scala.collection.immutable.HashMap.apply(HashMap.scala:132)
	at stainless.extraction.imperative.EffectsAnalyzer$EffectsAnalysis.effects(EffectsAnalyzer.scala:143)
	at stainless.extraction.imperative.EffectsAnalyzer$EffectsAnalysis.effects$(EffectsAnalyzer.scala:86)
	at stainless.extraction.imperative.AntiAliasing$SymbolsAnalysis.effects(AntiAliasing.scala:44)
	at stainless.extraction.imperative.EffectsAnalyzer$EffectsAnalysis.getAliasedParams(EffectsAnalyzer.scala:149)
	at stainless.extraction.imperative.EffectsAnalyzer$EffectsAnalysis.getAliasedParams$(EffectsAnalyzer.scala:86)
	at stainless.extraction.imperative.AntiAliasing$SymbolsAnalysis.getAliasedParams(AntiAliasing.scala:44)
	at stainless.extraction.imperative.AntiAliasing.stainless$extraction$imperative$AntiAliasing$$_$updateFunction$1(AntiAliasing.scala:122)
	at stainless.extraction.imperative.AntiAliasing$TransformerImpl$1.$anonfun$12(AntiAliasing.scala:460)
	at scala.collection.immutable.List.map(List.scala:246)
	at scala.collection.immutable.List.map(List.scala:79)
	at stainless.extraction.imperative.AntiAliasing$TransformerImpl$1.transform(AntiAliasing.scala:460)
	at stainless.extraction.imperative.AntiAliasing$TransformerImpl$1.transform(AntiAliasing.scala:475)
	at stainless.extraction.imperative.AntiAliasing$TransformerImpl$1.$anonfun$15(AntiAliasing.scala:502)
	at scala.collection.immutable.List.map(List.scala:250)
	at scala.collection.immutable.List.map(List.scala:79)
	at stainless.extraction.imperative.AntiAliasing$TransformerImpl$1.transform(AntiAliasing.scala:502)
	at stainless.extraction.imperative.AntiAliasing$TransformerImpl$1.transform$$anonfun$8(AntiAliasing.scala:546)
	at scala.collection.immutable.List.map(List.scala:246)
	at scala.collection.immutable.List.map(List.scala:79)
	at stainless.extraction.imperative.AntiAliasing$TransformerImpl$1.transform(AntiAliasing.scala:546)
	at stainless.extraction.imperative.AntiAliasing$TransformerImpl$1.transform$$anonfun$8(AntiAliasing.scala:546)
	at scala.collection.immutable.List.map(List.scala:250)
	at scala.collection.immutable.List.map(List.scala:79)
	at stainless.extraction.imperative.AntiAliasing$TransformerImpl$1.transform(AntiAliasing.scala:546)
	at stainless.extraction.imperative.AntiAliasing.makeSideEffectsExplicit$1(AntiAliasing.scala:551)
	at stainless.extraction.imperative.AntiAliasing.stainless$extraction$imperative$AntiAliasing$$_$updateFunction$1(AntiAliasing.scala:126)
	at stainless.extraction.imperative.AntiAliasing.extractFunction(AntiAliasing.scala:640)
	at stainless.extraction.imperative.AntiAliasing.extractFunction(AntiAliasing.scala:85)
	at stainless.extraction.CachingPhase.$anonfun$3$$anonfun$1(ExtractionPipeline.scala:102)
	at stainless.extraction.utils.ConcurrentCache.cached(ConcurrentCaches.scala:26)
	at stainless.extraction.ExtractionCaches$ExtractionCache.cached(ExtractionCaches.scala:165)
	at stainless.extraction.CachingPhase.$anonfun$1(ExtractionPipeline.scala:102)
	at scala.collection.Iterator$$anon$9.next(Iterator.scala:575)
	at scala.collection.immutable.List.prependedAll(List.scala:156)
	at scala.collection.immutable.List$.from(List.scala:684)
	at scala.collection.immutable.List$.from(List.scala:681)
	at scala.collection.IterableFactory$Delegate.from(Factory.scala:288)
	at scala.collection.immutable.Iterable$.from(Iterable.scala:35)
	at scala.collection.immutable.Iterable$.from(Iterable.scala:32)
	at scala.collection.IterableFactory$Delegate.from(Factory.scala:288)
	at scala.collection.IterableOps.map(Iterable.scala:671)
	at scala.collection.IterableOps.map$(Iterable.scala:671)
	at scala.collection.AbstractIterable.map(Iterable.scala:919)
	at stainless.extraction.CachingPhase.extractSymbols(ExtractionPipeline.scala:102)
	at stainless.extraction.CachingPhase.extractSymbols$(ExtractionPipeline.scala:82)
	at stainless.extraction.imperative.AntiAliasing.stainless$extraction$oo$CachingPhase$$super$extractSymbols(AntiAliasing.scala:11)
	at stainless.extraction.imperative.AntiAliasing.stainless$extraction$oo$CachingPhase$$super$extractSymbols(AntiAliasing.scala:11)
	at stainless.extraction.oo.CachingPhase.extractSymbols(ExtractionPipeline.scala:28)
	at stainless.extraction.oo.CachingPhase.extractSymbols$(ExtractionPipeline.scala:13)
	at stainless.extraction.imperative.AntiAliasing.extractSymbols(AntiAliasing.scala:11)
	at stainless.extraction.imperative.AntiAliasing.extractSymbols(AntiAliasing.scala:11)
	at stainless.extraction.CachingPhase.extract(ExtractionPipeline.scala:97)
	at stainless.extraction.CachingPhase.extract$(ExtractionPipeline.scala:82)
	at stainless.extraction.imperative.AntiAliasing.extract(AntiAliasing.scala:11)
	at stainless.extraction.utils.DebugPipeline.extract$$anonfun$2$$anonfun$1(DebugPipeline.scala:136)
	at scala.util.Try$.apply(Try.scala:210)
	at inox.utils.TimerStorage.runAndGetTime(Timer.scala:93)
	at inox.utils.TimerStorage.run(Timer.scala:88)
	at stainless.extraction.utils.DebugPipeline.extract$$anonfun$1(DebugPipeline.scala:136)
	at stainless.extraction.utils.DebugSymbols.debug(DebugPipeline.scala:64)
	at stainless.extraction.utils.DebugSymbols.debug$(DebugPipeline.scala:29)
	at stainless.extraction.utils.DebugPipeline.debug(DebugPipeline.scala:124)
	at stainless.extraction.utils.DebugPipeline.extract(DebugPipeline.scala:137)
	at stainless.extraction.ExtractionPipeline$AndThenImpl$1.extract(ExtractionPipeline.scala:30)
	at stainless.extraction.ExtractionPipeline$AndThenImpl$1.extract(ExtractionPipeline.scala:30)
	at stainless.extraction.ExtractionPipeline$AndThenImpl$1.extract(ExtractionPipeline.scala:30)
	at stainless.extraction.ExtractionPipeline$AndThenImpl$1.extract(ExtractionPipeline.scala:30)
	at stainless.extraction.ExtractionPipeline$AndThenImpl$1.extract(ExtractionPipeline.scala:30)
	at stainless.extraction.ExtractionPipeline$AndThenImpl$1.extract(ExtractionPipeline.scala:30)
	at stainless.extraction.ExtractionPipeline$AndThenImpl$1.extract(ExtractionPipeline.scala:30)
	at stainless.extraction.ExtractionPipeline$AndThenImpl$1.extract(ExtractionPipeline.scala:30)
	at stainless.extraction.ExtractionPipeline$AndThenImpl$1.extract(ExtractionPipeline.scala:30)
	at stainless.extraction.ExtractionPipeline$AndThenImpl$1.extract(ExtractionPipeline.scala:30)
	at stainless.extraction.ExtractionPipeline$AndThenImpl$1.extract(ExtractionPipeline.scala:30)
	at stainless.extraction.ExtractionPipeline$AndThenImpl$1.extract(ExtractionPipeline.scala:30)
	at stainless.extraction.ExtractionPipeline$AndThenImpl$1.extract(ExtractionPipeline.scala:30)
	at stainless.ComponentRun.extract(Component.scala:87)
	at stainless.ComponentRun.extract$(Component.scala:47)
	at stainless.verification.VerificationRun.extract(VerificationComponent.scala:53)
	at stainless.ComponentRun.apply(Component.scala:97)
	at stainless.ComponentRun.apply$(Component.scala:47)
	at stainless.verification.VerificationRun.apply(VerificationComponent.scala:53)
	at stainless.frontend.SplitCallBack.$anonfun$8(SplitCallBack.scala:196)
	at scala.collection.immutable.List.map(List.scala:246)
	at scala.collection.immutable.List.map(List.scala:79)
	at stainless.frontend.SplitCallBack.processFunctionsSymbols(SplitCallBack.scala:198)
	at stainless.frontend.SplitCallBack.$anonfun$7(SplitCallBack.scala:170)
	at stainless.extraction.utils.ConcurrentCache.getOrElseUpdate(ConcurrentCaches.scala:15)
	at stainless.frontend.SplitCallBack.processFunctions(SplitCallBack.scala:170)
	at stainless.frontend.SplitCallBack.processSymbols(SplitCallBack.scala:156)
	at stainless.frontend.SplitCallBack.endExtractions(SplitCallBack.scala:78)
	at stainless.frontend.ThreadedFrontend$$anon$1.run(ThreadedFrontend.scala:34)
	at java.lang.Thread.run(Thread.java:750)
</code>
</details>

The error must come from the fact that the passed lambda has type `(BigInt, BigInt) => (BigInt, BigInt)`, whereas the function expects `((BigInt, BigInt)) => (BigInt, BigInt)` (notice the extra pair of parentheses). 

Note however that the following variation works just fine:
```scala
import stainless.collection.*

object Test {
  def f(l: List[(BigInt, BigInt)]): Unit = {
    val f: ((BigInt, BigInt)) => (BigInt, BigInt) = (x, y) => (x, y)
    val _ = l.map( f )
    ()
  }
}
```

**Comment by mario-bucev** [comment]
I cannot reproduce this exact issue, but here is one that seems to have the same root issue:
```scala
import stainless.lang._
object Tayst {

  def f: Unit = {
    val lam = (x: BigInt) => {
      def nasty = x + x
      nasty
    }
    val lam2 = (x: BigInt) => {
      def nasty2 = x + x + x
      nasty2
    }
    assert(lam2(0) == 0)
  }
}
```
The problem stems from having functions defined in lambdas (an interesting idea), but it turns out that this what happens when using the auto-tupling feature.
