### ISSUE TITLE
Inner recursive function returning tuple and destructing it yields `MatchError: <untyped>`

### ISSUE THREAD

**Issue by Ef55** [epfl-lara/stainless#1303]
As oddly specific as the title might sound the following crashes stainless
```scala
object Test {
  def outer: Unit = {
    def inner: (BigInt, BigInt) = {
      val (_, _) = inner
      (0, 0)
    }
    ()
  }
}
```
<details>
<summary>stainless-stack-trace.txt</summary>
<code>
scala.MatchError: <untyped> (of class inox.ast.Types$Untyped$)
	at stainless.ast.SymbolOps$PatternConditions.apply(SymbolOps.scala:86)
	at stainless.ast.SymbolOps.conditionForPattern(SymbolOps.scala:123)
	at stainless.ast.SymbolOps.conditionForPattern$(SymbolOps.scala:9)
	at stainless.extraction.innerfuns.package$trees$Symbols.conditionForPattern(package.scala:9)
	at stainless.transformers.TransformerWithPC.transformCases$$anonfun$1(TransformerWithPC.scala:44)
	at scala.collection.immutable.List.map(List.scala:246)
	at scala.collection.immutable.List.map(List.scala:79)
	at stainless.transformers.TransformerWithPC.transformCases(TransformerWithPC.scala:56)
	at stainless.transformers.TransformerWithPC.transform(TransformerWithPC.scala:34)
	at stainless.transformers.TransformerWithPC.transform$(TransformerWithPC.scala:6)
	at stainless.extraction.innerfuns.SymbolOps$Impl$1.stainless$extraction$innerfuns$TransformerWithPC$$super$transform(SymbolOps.scala:18)
	at stainless.extraction.innerfuns.TransformerWithPC.transform(TransformerWithPC.scala:31)
	at stainless.extraction.innerfuns.TransformerWithPC.transform$(TransformerWithPC.scala:7)
	at stainless.extraction.innerfuns.SymbolOps$Impl$1.inox$transformers$TransformerWithExprOp$$super$transform(SymbolOps.scala:18)
	at stainless.extraction.innerfuns.SymbolOps$Impl$1.inox$transformers$TransformerWithExprOp$$super$transform(SymbolOps.scala:18)
	at inox.transformers.TransformerWithExprOp.$init$$$anonfun$2(TransformerOps.scala:11)
	at inox.ast.SymbolOps.collectWithPC$$anonfun$1(SymbolOps.scala:146)
	at stainless.extraction.innerfuns.SymbolOps$Impl$1.exprOp(SymbolOps.scala:27)
	at stainless.extraction.innerfuns.SymbolOps$Impl$1.exprOp(SymbolOps.scala:26)
	at inox.transformers.TransformerWithExprOp.transform(TransformerOps.scala:15)
	at inox.transformers.TransformerWithExprOp.transform$(TransformerOps.scala:10)
	at stainless.extraction.innerfuns.SymbolOps$Impl$1.transform(SymbolOps.scala:18)
	at stainless.extraction.innerfuns.SymbolOps$Impl$1.transform(SymbolOps.scala:18)
	at inox.transformers.TransformerWithPC.transform(TransformerWithPC.scala:12)
	at inox.transformers.TransformerWithPC.transform$(TransformerWithPC.scala:7)
	at stainless.extraction.innerfuns.SymbolOps$Impl$1.stainless$transformers$Transformer$$super$transform(SymbolOps.scala:18)
	at stainless.extraction.innerfuns.SymbolOps$Impl$1.stainless$transformers$Transformer$$super$transform(SymbolOps.scala:18)
	at stainless.transformers.Transformer.transform(Transformer.scala:63)
	at stainless.transformers.Transformer.transform$(Transformer.scala:8)
	at stainless.extraction.innerfuns.SymbolOps$Impl$1.stainless$transformers$TransformerWithPC$$super$transform(SymbolOps.scala:18)
	at stainless.transformers.TransformerWithPC.transform(TransformerWithPC.scala:36)
	at stainless.transformers.TransformerWithPC.transform$(TransformerWithPC.scala:6)
	at stainless.extraction.innerfuns.SymbolOps$Impl$1.stainless$extraction$innerfuns$TransformerWithPC$$super$transform(SymbolOps.scala:18)
	at stainless.extraction.innerfuns.TransformerWithPC.transform(TransformerWithPC.scala:31)
	at stainless.extraction.innerfuns.TransformerWithPC.transform$(TransformerWithPC.scala:7)
	at stainless.extraction.innerfuns.SymbolOps$Impl$1.inox$transformers$TransformerWithExprOp$$super$transform(SymbolOps.scala:18)
	at stainless.extraction.innerfuns.SymbolOps$Impl$1.inox$transformers$TransformerWithExprOp$$super$transform(SymbolOps.scala:18)
	at inox.transformers.TransformerWithExprOp.$init$$$anonfun$2(TransformerOps.scala:11)
	at inox.ast.SymbolOps.collectWithPC$$anonfun$1(SymbolOps.scala:146)
	at stainless.extraction.innerfuns.SymbolOps$Impl$1.exprOp(SymbolOps.scala:27)
	at stainless.extraction.innerfuns.SymbolOps$Impl$1.exprOp(SymbolOps.scala:26)
	at inox.transformers.TransformerWithExprOp.transform(TransformerOps.scala:15)
	at inox.transformers.TransformerWithExprOp.transform$(TransformerOps.scala:10)
	at stainless.extraction.innerfuns.SymbolOps$Impl$1.transform(SymbolOps.scala:18)
	at stainless.extraction.innerfuns.SymbolOps$Impl$1.transform(SymbolOps.scala:18)
	at inox.ast.SymbolOps.transformWithPC(SymbolOps.scala:122)
	at inox.ast.SymbolOps.transformWithPC$(SymbolOps.scala:27)
	at inox.ast.SimpleSymbols$SimpleSymbols.transformWithPC(SimpleSymbols.scala:12)
	at inox.ast.SymbolOps.collectWithPC(SymbolOps.scala:147)
	at inox.ast.SymbolOps.collectWithPC$(SymbolOps.scala:27)
	at inox.ast.SimpleSymbols$SimpleSymbols.collectWithPC(SimpleSymbols.scala:12)
	at inox.ast.SymbolOps.collectWithPC(SymbolOps.scala:156)
	at inox.ast.SymbolOps.collectWithPC$(SymbolOps.scala:27)
	at inox.ast.SimpleSymbols$SimpleSymbols.collectWithPC(SimpleSymbols.scala:12)
	at inox.ast.SymbolOps.collectWithPC(SymbolOps.scala:158)
	at inox.ast.SymbolOps.collectWithPC$(SymbolOps.scala:27)
	at inox.ast.SimpleSymbols$SimpleSymbols.collectWithPC(SimpleSymbols.scala:12)
	at stainless.extraction.innerfuns.FunctionClosure.close$1(FunctionClosure.scala:114)
	at stainless.extraction.innerfuns.FunctionClosure.close$2$$anonfun$1(FunctionClosure.scala:218)
	at scala.collection.immutable.List.flatMap(List.scala:293)
	at stainless.extraction.innerfuns.FunctionClosure.close$1(FunctionClosure.scala:218)
	at stainless.extraction.innerfuns.FunctionClosure.extractFunction(FunctionClosure.scala:221)
	at stainless.extraction.innerfuns.FunctionClosure.extractFunction(FunctionClosure.scala:20)
	at stainless.extraction.CachingPhase.$anonfun$3$$anonfun$1(ExtractionPipeline.scala:102)
	at stainless.extraction.utils.ConcurrentCache.cached(ConcurrentCaches.scala:26)
	at stainless.extraction.ExtractionCaches$ExtractionCache.cached(ExtractionCaches.scala:165)
	at stainless.extraction.CachingPhase.$anonfun$1(ExtractionPipeline.scala:102)
	at scala.collection.Iterator$$anon$9.next(Iterator.scala:575)
	at scala.collection.immutable.List.prependedAll(List.scala:153)
	at scala.collection.immutable.List$.from(List.scala:684)
	at scala.collection.immutable.List$.from(List.scala:681)
	at scala.collection.IterableFactory$Delegate.from(Factory.scala:288)
	at scala.collection.immutable.Iterable$.from(Iterable.scala:35)
	at scala.collection.immutable.Iterable$.from(Iterable.scala:32)
	at scala.collection.IterableFactory$Delegate.from(Factory.scala:288)
	at scala.collection.IterableOps.map(Iterable.scala:671)
	at scala.collection.IterableOps.map$(Iterable.scala:671)
	at scala.collection.AbstractIterable.map(Iterable.scala:919)
	at stainless.extraction.CachingPhase.extractSymbols(ExtractionPipeline.scala:102)
	at stainless.extraction.CachingPhase.extractSymbols$(ExtractionPipeline.scala:82)
	at stainless.extraction.innerfuns.FunctionClosure.extractSymbols(FunctionClosure.scala:7)
	at stainless.extraction.CachingPhase.extract(ExtractionPipeline.scala:97)
	at stainless.extraction.CachingPhase.extract$(ExtractionPipeline.scala:82)
	at stainless.extraction.innerfuns.FunctionClosure.extract(FunctionClosure.scala:7)
	at stainless.extraction.utils.DebugPipeline.extract$$anonfun$2$$anonfun$1(DebugPipeline.scala:136)
	at scala.util.Try$.apply(Try.scala:210)
	at inox.utils.TimerStorage.runAndGetTime(Timer.scala:93)
	at inox.utils.TimerStorage.run(Timer.scala:88)
	at stainless.extraction.utils.DebugPipeline.extract$$anonfun$1(DebugPipeline.scala:136)
	at stainless.extraction.utils.DebugSymbols.debug(DebugPipeline.scala:64)
	at stainless.extraction.utils.DebugSymbols.debug$(DebugPipeline.scala:29)
	at stainless.extraction.utils.DebugPipeline.debug(DebugPipeline.scala:124)
	at stainless.extraction.utils.DebugPipeline.extract(DebugPipeline.scala:137)
	at stainless.extraction.ExtractionPipeline$AndThenImpl$1.extract(ExtractionPipeline.scala:30)
	at stainless.extraction.ExtractionPipeline$AndThenImpl$1.extract(ExtractionPipeline.scala:30)
	at stainless.extraction.ExtractionPipeline$AndThenImpl$1.extract(ExtractionPipeline.scala:30)
	at stainless.extraction.ExtractionPipeline$AndThenImpl$1.extract(ExtractionPipeline.scala:30)
	at stainless.extraction.ExtractionPipeline$AndThenImpl$1.extract(ExtractionPipeline.scala:30)
	at stainless.extraction.ExtractionPipeline$AndThenImpl$1.extract(ExtractionPipeline.scala:30)
	at stainless.extraction.ExtractionPipeline$AndThenImpl$1.extract(ExtractionPipeline.scala:30)
	at stainless.ComponentRun.extract(Component.scala:87)
	at stainless.ComponentRun.extract$(Component.scala:47)
	at stainless.verification.VerificationRun.extract(VerificationComponent.scala:53)
	at stainless.ComponentRun.apply(Component.scala:97)
	at stainless.ComponentRun.apply$(Component.scala:47)
	at stainless.verification.VerificationRun.apply(VerificationComponent.scala:53)
	at stainless.frontend.SplitCallBack.$anonfun$8(SplitCallBack.scala:196)
	at scala.collection.immutable.List.map(List.scala:246)
	at scala.collection.immutable.List.map(List.scala:79)
	at stainless.frontend.SplitCallBack.processFunctionsSymbols(SplitCallBack.scala:198)
	at stainless.frontend.SplitCallBack.$anonfun$7(SplitCallBack.scala:170)
	at stainless.extraction.utils.ConcurrentCache.getOrElseUpdate(ConcurrentCaches.scala:15)
	at stainless.frontend.SplitCallBack.processFunctions(SplitCallBack.scala:170)
	at stainless.frontend.SplitCallBack.processSymbols(SplitCallBack.scala:156)
	at stainless.frontend.SplitCallBack.endExtractions(SplitCallBack.scala:78)
	at stainless.frontend.ThreadedFrontend$$anon$1.run(ThreadedFrontend.scala:34)
	at java.lang.Thread.run(Thread.java:750)
</code>
</details>

even though all of the following variations do not:
- Un-nesting the functions:
```scala
object Test {
  def inner: (BigInt, BigInt) = {
    val (_, _) = inner
    (0, 0)
  }
  def outer: Unit = {
    ()
  }
}
```
- Not destructing the returned tuple:
```scala
object Test {
  def outer: Unit = {
    def inner: (BigInt, BigInt) = {
      inner
      (0, 0)
    }
    ()
  }
}
```
- Destructing something else (than the returned value)
```scala
object Test {
  def outer: Unit = {
    def inner: (BigInt, BigInt) = {
      val (_, _) = { inner; (0, 0) }
      (0, 0)
    }
    ()
  }
}
```

**Comment by vkuncak** [comment]
I cannot introduce this any more, @mario-bucev may have fixed it while resolving another issue.
The example provided is non-terminating and no measure is inferred, which is as desired. 
If there is another example, we should revisit.

**Comment by mario-bucev** [comment]
I remember not being able to reproduce it even before the fixes wave, but we can leave this issue open for now.
