### ISSUE TITLE
NullPointerException in PortfolioSolver

### ISSUE THREAD

**Issue by jad-hamza** [epfl-lara/stainless#212]
```scala
object Solver {
  def theorem() = {
    assert(true)
  }
}
```

> stainless-scalac --solvers=smt-z3,smt-cvc4 Test.scala 

```scala
[Internal] Error: null. Trace:                                                                                                                                                                                    
[Internal] - inox.solvers.combinators.PortfolioSolverFactory$class.$init$(PortfolioSolverFactory.scala:25)                                                                                                        
[Internal] - inox.solvers.combinators.PortfolioSolverFactory$$anon$2.<init>(PortfolioSolverFactory.scala:33)                                                                                                      
[Internal] - inox.solvers.combinators.PortfolioSolverFactory$.apply(PortfolioSolverFactory.scala:31)                                                                                                              
[Internal] - stainless.solvers.SolverFactory$.getFromNames(SolverFactory.scala:43)                                                                                                                                
[Internal] - stainless.solvers.SolverFactory$.getFromSettings(SolverFactory.scala:55)                                                                                                                             
[Internal] - stainless.solvers.SolverFactory$.apply(SolverFactory.scala:66)                                                                                                                                       
[Internal] - stainless.verification.VerificationChecker$Checker$1.getFactory(VerificationChecker.scala:166)                                                                                                       
[Internal] - stainless.verification.VerificationChecker$class.verify(VerificationChecker.scala:52)                                                                                                                
[Internal] - stainless.verification.VerificationChecker$Checker$1.verify(VerificationChecker.scala:162)                                                                                                           
[Internal] - stainless.verification.VerificationChecker$.verify(VerificationChecker.scala:175)                                                                                                                    
[Internal] - stainless.verification.VerificationComponent$.check(VerificationComponent.scala:46)
[Internal] - stainless.verification.VerificationComponent$.apply(VerificationComponent.scala:54)
[Internal] - stainless.verification.VerificationComponent$.apply(VerificationComponent.scala:15)
[Internal] - stainless.SimpleComponent$class.apply(Component.scala:87)
[Internal] - stainless.verification.VerificationComponent$.apply(VerificationComponent.scala:15)
[Internal] - stainless.verification.VerificationCallBack.solve(VerificationCallBack.scala:29)
[Internal] - stainless.verification.VerificationCallBack.solve(VerificationCallBack.scala:12)
[Internal] - stainless.frontend.CallBackWithRegistry$$anonfun$stainless$frontend$CallBackWithRegistry$$processProgram$1.apply(CallBackWithRegistry.scala:194)
[Internal] - stainless.frontend.CallBackWithRegistry$$anonfun$stainless$frontend$CallBackWithRegistry$$processProgram$1.apply(CallBackWithRegistry.scala:194)
[Internal] - scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
[Internal] - scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
[Internal] - scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
[Internal] - scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
[Internal] - scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
[Internal] - scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
[Internal] - scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Exception in thread "main" java.lang.NullPointerException
        at inox.Reporter.internalError(Reporter.scala:54)
        at inox.Reporter.internalError(Reporter.scala:100)
        at inox.Reporter.internalError(Reporter.scala:103)
        at stainless.MainHelpers$class.regularRunCycle$1(MainHelpers.scala:159)
        at stainless.MainHelpers$class.main(MainHelpers.scala:172)
        at stainless.Main$.main(Main.scala:3)
        at stainless.Main.main(Main.scala)
```

**Comment by samarion** [comment]
Fixed in https://github.com/epfl-lara/inox/commit/bc1ab6de86abde7fcb556c88868402f4a55b3c70 (will release and bump the Inox version once the symbolic simplifier is merged).
