### ISSUE TITLE
java.lang.StackOverflowError in Inox

### ISSUE THREAD

**Issue by jad-hamza** [epfl-lara/stainless#554]
```scala
import stainless.annotation._
import stainless.lang.MutableMap

// removing this import prevents the error
// because the normal non-ghost `ensuring(true)` in `ensureTrue`
// gets simplified away by RefinementLifting
import stainless.lang.StaticChecks._

import Lib._

object Lib {
  def ensureTrue(): Unit = {
    ()
  } ensuring(_ => true) // removing the ensuring prevents the error

  // removing the unused parameter `a` prevents the error
  def zero(a: BigInt): BigInt = {
    ensureTrue() // commenting this line prevents the error
    0
  }
}

@mutable
trait A

trait B extends A { // removing the inheritance from A prevents the error
  // removing one of x1 or x2 (unused) prevents the error
  var x1: BigInt
  var x2: BigInt

  val m: MutableMap[BigInt, BigInt]

  final def updateManyTimes() = {
    // removing one of these four lines prevents the error
    m(0) = zero(m(0))
    m(0) = zero(m(0))
    m(0) = zero(m(0))
    m(0) = zero(m(0))
  }
}
```

Various changes (see the code) prevent the error

```
[  Info  ]  - Now solving 'postcondition' VC for updateManyTimes @32:3...
Exception in thread "ForkJoinPool-1-worker-0" java.lang.StackOverflowError
        at inox.transformers.SimplifierWithPC.simplify(SimplifierWithPC.scala:92)
        at inox.transformers.SimplifierWithPC.simplify$(SimplifierWithPC.scala:92)
        at inox.ast.SymbolOps$$anon$1.simplify(SymbolOps.scala:33)
        at inox.transformers.SimplifierWithPC.simplify(SimplifierWithPC.scala:161)
        at inox.transformers.SimplifierWithPC.simplify$(SimplifierWithPC.scala:92)
        at inox.ast.SymbolOps$$anon$1.simplify(SymbolOps.scala:33)
        at inox.transformers.SimplifierWithPC.transform(SimplifierWithPC.scala:322)
        at inox.transformers.SimplifierWithPC.transform$(SimplifierWithPC.scala:320)
        at inox.ast.SymbolOps$$anon$1.transform(SymbolOps.scala:33)
        at inox.ast.SymbolOps$$anon$1.transform(SymbolOps.scala:33)
        at inox.transformers.Transformer.$anonfun$transform$4(Transformer.scala:70)
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:237)
        at scala.collection.immutable.List.foreach(List.scala:392)
        at scala.collection.TraversableLike.map(TraversableLike.scala:237)
        at scala.collection.TraversableLike.map$(TraversableLike.scala:230)
        at scala.collection.immutable.List.map(List.scala:298)
        at inox.transformers.Transformer.transform(Transformer.scala:69)
        at inox.transformers.Transformer.transform$(Transformer.scala:51)
        at inox.ast.SymbolOps$$anon$1.inox$transformers$SimplifierWithPC$$super$transform(SymbolOps.scala:33)
        at inox.transformers.SimplifierWithPC.simplify(SimplifierWithPC.scala:305)
        at inox.transformers.SimplifierWithPC.simplify$(SimplifierWithPC.scala:92)
        at inox.ast.SymbolOps$$anon$1.simplify(SymbolOps.scala:33)
        at inox.transformers.SimplifierWithPC.simplify(SimplifierWithPC.scala:230)
        at inox.transformers.SimplifierWithPC.simplify$(SimplifierWithPC.scala:92)
        at inox.ast.SymbolOps$$anon$1.simplify(SymbolOps.scala:33)
        at inox.transformers.SimplifierWithPC.simplify(SimplifierWithPC.scala:231)
        at inox.transformers.SimplifierWithPC.simplify$(SimplifierWithPC.scala:92)
        at inox.ast.SymbolOps$$anon$1.simplify(SymbolOps.scala:33)
        at inox.transformers.SimplifierWithPC.simplify(SimplifierWithPC.scala:231)
        at inox.transformers.SimplifierWithPC.simplify$(SimplifierWithPC.scala:92)
        at inox.ast.SymbolOps$$anon$1.simplify(SymbolOps.scala:33)
        at inox.transformers.SimplifierWithPC.simplify(SimplifierWithPC.scala:231)
        at inox.transformers.SimplifierWithPC.simplify$(SimplifierWithPC.scala:92)
        at inox.ast.SymbolOps$$anon$1.simplify(SymbolOps.scala:33)
       [...]
```

**Comment by jad-hamza** [comment]
This is fixed when we remove the call to `mergeFunctions` in https://github.com/epfl-lara/inox/blob/a6cbf8e2488fd2d3aa941963fca65eb5d370c698/src/main/scala/inox/ast/SymbolOps.scala#L1214, or when we execute it last instead of first.

I've tried removing the call completely and running Stainless tests and bolts to see if that slowed them down but that seemed to have no effect

**Comment by jad-hamza** [comment]
The issue might come from `liftCalls` https://github.com/epfl-lara/inox/blob/a6cbf8e2488fd2d3aa941963fca65eb5d370c698/src/main/scala/inox/ast/SymbolOps.scala#L1033, though I'm not sure. Could `FunctionInvocation`'s be lifted outside of their scope? (For instance outside lambdas?).

@samarion Do you think we can remove `mergeFunctions` completely, since it doesn't seem to affect performance (that would need to be confirmed with further tests). I've created a PR in case you think it's a good idea https://github.com/epfl-lara/inox/pull/103.

**Comment by jad-hamza** [comment]
As far as I can tell, the issue is that `mergeFunctions` creates many nested `Let`'s, which leads to a StackOverflow. Increasing the stack size using `-J-Xss` solves the issue. We can reopen to discuss potential optimizations if this problem ever reoccurs.
