### ISSUE TITLE
traceback: asInstanceOf can only cast to Class types

### ISSUE THREAD

**Issue by saraswat** [epfl-lara/stainless#760]
Can someone shed light on this please?

I wonder whether it is worth checking for all places where this exception is being thrown in the source code of stainless. Should produce a better approximation of what has been implemented...

```
Error:scalac: Error: asInstanceOf can only cast to class types
stainless.frontend.package$UnsupportedCodeException: asInstanceOf can only cast to class types
	at stainless.frontends.scalac.CodeExtraction.outOfSubsetError(CodeExtraction.scala:95)
	at stainless.frontends.scalac.CodeExtraction.extractTree(CodeExtraction.scala:1228)
	at stainless.frontends.scalac.CodeExtraction.rec$2(CodeExtraction.scala:879)
	at stainless.frontends.scalac.CodeExtraction.rec$2(CodeExtraction.scala:879)
	at stainless.frontends.scalac.CodeExtraction.extractBlock(CodeExtraction.scala:907)
	at stainless.frontends.scalac.CodeExtraction.extractTree(CodeExtraction.scala:922)
	at stainless.frontends.scalac.CodeExtraction.extractTreeOrNoTree(CodeExtraction.scala:781)
	at stainless.frontends.scalac.CodeExtraction.extractFunction(CodeExtraction.scala:605)
	at stainless.frontends.scalac.CodeExtraction.$anonfun$extractStatic$1(CodeExtraction.scala:261)
	at stainless.frontends.scalac.CodeExtraction.$anonfun$extractStatic$1$adapted(CodeExtraction.scala:209)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at stainless.frontends.scalac.CodeExtraction.extractStatic(CodeExtraction.scala:209)
	at stainless.frontends.scalac.CodeExtraction.extractObject(CodeExtraction.scala:336)
	at stainless.frontends.scalac.CodeExtraction.$anonfun$extractStatic$1(CodeExtraction.scala:240)
	at stainless.frontends.scalac.CodeExtraction.$anonfun$extractStatic$1$adapted(CodeExtraction.scala:209)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at stainless.frontends.scalac.CodeExtraction.extractStatic(CodeExtraction.scala:209)
	at stainless.frontends.scalac.CodeExtraction.extractUnit(CodeExtraction.scala:57)
	at stainless.frontends.scalac.CodeExtraction.extractUnit$(CodeExtraction.scala:44)
	at stainless.frontends.scalac.StainlessPluginComponent.extractUnit(StainlessPlugin.scala:86)
	at stainless.frontends.scalac.StainlessExtraction$Phase.apply(StainlessExtraction.scala:39)
	at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:453)
	at scala.tools.nsc.Global$GlobalPhase.run(Global.scala:399)
	at stainless.frontends.scalac.StainlessExtraction$Phase.super$run(StainlessExtraction.scala:45)
	at stainless.frontends.scalac.StainlessExtraction$Phase.$anonfun$run$1(StainlessExtraction.scala:45)
	at stainless.frontends.scalac.StainlessPluginComponent.onRun(StainlessPlugin.scala:116)
	at stainless.frontends.scalac.StainlessExtraction$Phase.run(StainlessExtraction.scala:45)
	at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1503)
	at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1487)
	at scala.tools.nsc.Global$Run.compileSources(Global.scala:1480)
	at scala.tools.nsc.Global$Run.compile(Global.scala:1606)
	at xsbt.CachedCompiler0.run(CompilerInterface.scala:130)
	at xsbt.CachedCompiler0.run(CompilerInterface.scala:105)
	at xsbt.CompilerInterface.run(CompilerInterface.scala:31)
	at sun.reflect.GeneratedMethodAccessor14.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sbt.internal.inc.AnalyzingCompiler.call(AnalyzingCompiler.scala:237)
	at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:111)
	at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:90)
	at org.jetbrains.jps.incremental.scala.local.IdeaIncrementalCompiler.compile(IdeaIncrementalCompiler.scala:42)
	at org.jetbrains.jps.incremental.scala.local.LocalServer.compile(LocalServer.scala:43)
	at org.jetbrains.jps.incremental.scala.remote.Main$.compileLogic(Main.scala:117)
	at org.jetbrains.jps.incremental.scala.remote.Main$.handleCommand(Main.scala:109)
	at org.jetbrains.jps.incremental.scala.remote.Main$.serverLogic(Main.scala:95)
	at org.jetbrains.jps.incremental.scala.remote.Main$.nailMain(Main.scala:53)
	at org.jetbrains.jps.incremental.scala.remote.Main.nailMain(Main.scala)
	at sun.reflect.GeneratedMethodAccessor11.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.martiansoftware.nailgun.NGSession.run(NGSession.java:319)
```

**Comment by romac** [comment]
> Can someone shed light on this please?

Stainless only supports casts between "class" types, as opposed to what we consider "primitive" or "built-in" types like `String`, `Int`, `Boolean`, `Array`, `Map`, `Set`, etc.

> I wonder whether it is worth checking for all places where this exception is being thrown in the source code of stainless. Should produce a better approximation of what has been implemented...

Agreed, there's some ongoing work in #756 to improve error handling and reporting.

**Comment by samarion** [comment]
Actually, I don't think this is a real constraint anymore after type encoding. I believe we should be able to cast between primitive types as well.

**Comment by saraswat** [comment]
@samarion The real value (for the user) is in casting to a parametric type, `T`.

**Comment by samarion** [comment]
@saraswat parametric types should work as well. I would suggest removing the check in [CodeExtraction](https://github.com/epfl-lara/stainless/blob/dae38d196c2a9f097391886fc12404bccf5b7d5b/frontends/scalac/src/main/scala/stainless/frontends/scalac/CodeExtraction.scala#L1228) and seeing if something breaks.
