### ISSUE TITLE
Traceback:  missed generic inference leads to (a mistaken) unsupported feature

### ISSUE THREAD

**Issue by saraswat** [epfl-lara/stainless#764]
This snippet abstracts from some real code.

scalac is happy with this (as it should be):
```
abstract class A
abstract class B[X] {
  def p: Unit
} 
abstract class C[X <: A, Y <:  C[X, Y]]  extends B[X]
abstract class D [X  <: C[A, X]] {
   def m(x: X): Unit = {
     x.p
   }
}
```

But stainless tracebacks:
```
 ## Exception when compiling 31 sources to /Users/savija/tmp/test/verified/target/scala-2.12/classes
[error] stainless.frontend.package$UnsupportedCodeException: Unknown call to p on x (X) with arguments List() of type List()
[error] stainless.frontends.scalac.CodeExtraction.outOfSubsetError(CodeExtraction.scala:95)
[error] stainless.frontends.scalac.CodeExtraction.extractTree(CodeExtraction.scala:1518)
[error] stainless.frontends.scalac.CodeExtraction.extractTreeOrNoTree(CodeExtraction.scala:781)
[error] stainless.frontends.scalac.CodeExtraction.extractFunction(CodeExtraction.scala:605)
[error] stainless.frontends.scalac.CodeExtraction.$anonfun$extractClass$12(CodeExtraction.scala:440)
[error] stainless.frontends.scalac.CodeExtraction.$anonfun$extractClass$12$adapted(CodeExtraction.scala:413)
[error] scala.collection.immutable.List.foreach(List.scala:392)
[error] stainless.frontends.scalac.CodeExtraction.extractClass(CodeExtraction.scala:413)
[error] stainless.frontends.scalac.CodeExtraction.$anonfun$extractStatic$1(CodeExtraction.scala:254)
[error] stainless.frontends.scalac.CodeExtraction.$anonfun$extractStatic$1$adapted(CodeExtraction.scala:209)
[error] scala.collection.immutable.List.foreach(List.scala:392)
[error] stainless.frontends.scalac.CodeExtraction.extractStatic(CodeExtraction.scala:209)
[error] stainless.frontends.scalac.CodeExtraction.extractUnit(CodeExtraction.scala:57)
[error] stainless.frontends.scalac.CodeExtraction.extractUnit$(CodeExtraction.scala:44)
[error] stainless.frontends.scalac.StainlessPluginComponent.extractUnit(StainlessPlugin.scala:86)
[error] stainless.frontends.scalac.StainlessExtraction$Phase.apply(StainlessExtraction.scala:39)
[error] scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:453)
[error] scala.tools.nsc.Global$GlobalPhase.run(Global.scala:399)
[error] stainless.frontends.scalac.StainlessExtraction$Phase.super$run(StainlessExtraction.scala:45)
[error] stainless.frontends.scalac.StainlessExtraction$Phase.$anonfun$run$1(StainlessExtraction.scala:45)
[error] stainless.frontends.scalac.StainlessPluginComponent.onRun(StainlessPlugin.scala:116)
[error] stainless.frontends.scalac.StainlessExtraction$Phase.run(StainlessExtraction.scala:45)
[error] scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1503)
[error] scala.tools.nsc.Global$Run.compileUnits(Global.scala:1487)
[error] scala.tools.nsc.Global$Run.compileSources(Global.scala:1480)
[error] scala.tools.nsc.Global$Run.compile(Global.scala:1606)

```

**Comment by romac** [comment]
Note: This could either be a bug in type encoding or just a pattern that's currently unsupported. Marking as `bug` until we figure out which it is.

**Comment by saraswat** [comment]
Here is code on a much simpler generic type which also exhibits this problem:

This code compiles and runs in Scala (as expected):
```
object MethodOnGenericTypeMissing {
  abstract class C {
    def getC: C
  }
  abstract class B  extends C {}
  case class A[T <: B]() {
    def m(t:T): C = t.getC
  }
  def main(a: Array[String]): Unit = {
    case class BB() extends B {
      override def getC:C = this
      override def toString(): String = "<A BB>"
    }
    println(new A[BB].m(new BB))
  }
}
```
(Ignore the `main` method, that is just to get a concrete output, the problem is the definition of `m`.)

Stainless gives a traceback:
```
[error] ## Exception when compiling 31 sources to /Users/savija/IdeaProjects/cake/stainless_test/verified/target/scala-2.12/classes
[error] stainless.frontend.package$UnsupportedCodeException: Unknown call to getC on t (T) with arguments List() of type List()
[error] stainless.frontends.scalac.CodeExtraction.outOfSubsetError(CodeExtraction.scala:95)
[error] stainless.frontends.scalac.CodeExtraction.extractTree(CodeExtraction.scala:1518)
[error] stainless.frontends.scalac.CodeExtraction.extractTreeOrNoTree(CodeExtraction.scala:781)
[error] stainless.frontends.scalac.CodeExtraction.extractFunction(CodeExtraction.scala:605)
[error] stainless.frontends.scalac.CodeExtraction.$anonfun$extractClass$12(CodeExtraction.scala:440)
[error] stainless.frontends.scalac.CodeExtraction.$anonfun$extractClass$12$adapted(CodeExtraction.scala:413)
[error] scala.collection.immutable.List.foreach(List.scala:392)
[error] stainless.frontends.scalac.CodeExtraction.extractClass(CodeExtraction.scala:413)
[error] stainless.frontends.scalac.CodeExtraction.$anonfun$extractStatic$1(CodeExtraction.scala:254)
[error] stainless.frontends.scalac.CodeExtraction.$anonfun$extractStatic$1$adapted(CodeExtraction.scala:209)
[error] scala.collection.immutable.List.foreach(List.scala:392)
[error] stainless.frontends.scalac.CodeExtraction.extractStatic(CodeExtraction.scala:209)
[error] stainless.frontends.scalac.CodeExtraction.extractObject(CodeExtraction.scala:336)
[error] stainless.frontends.scalac.CodeExtraction.$anonfun$extractStatic$1(CodeExtraction.scala:240)
...
```

**Comment by saraswat** [comment]
In fact this much simpler code raises the same problem:
```
 abstract class B  /*extends C */ {
    def get: B
  }
  case class A[T <: B]() {
    def m(t:T): B = t.get
  }
```

**Comment by saraswat** [comment]
Any progress on this -- still see this problem in my new code base.

**Comment by samarion** [comment]
Looks like we're not widening `T` to `B` when trying to lookup the method call inside CodeExtraction. This can probably be fixed by widening the extracted type before doing the pattern matching here: https://github.com/epfl-lara/stainless/blob/0b28e1e05af4b522425cee0d6ce6d0ee2e385b47/frontends/scalac/src/main/scala/stainless/frontends/scalac/CodeExtraction.scala#L1304

Something like
```scala
def widenToReal(tpe: Type): Type = tpe match {
  case tp: TypeParameter => widenToReal(tp.upperBound)
  case _ => tpe
}

...

case Some(lhs) => widenToReal(extractType(lhs)(dctx.setResolveTypes(true))) match {
```

**Comment by jad-hamza** [comment]
@samarion I saw this function which looks similar: https://github.com/epfl-lara/stainless/blob/0b28e1e05af4b522425cee0d6ce6d0ee2e385b47/core/src/main/scala/stainless/extraction/oo/Trees.scala#L161-L165 but it requires symbols (like `upperBound`).

**Comment by samarion** [comment]
I believe `tp.upperBound` doesn't need symbols (see implicit class in `oo.Definitions.scala`).

But this is a good point, my proposal won't fix the case where `lhs` is a type application instead of a type parameter (and we can't widen those without the symbols). Maybe we can rely on the scalac type checker to do the widening for us? Something like `extractType(lhs.tpe.widen)(dctx.setResolveTypes(true))`. I'm not sure what widening operations scalac will apply here though, might be worth checking the doc.

**Comment by jad-hamza** [comment]
Thanks for the suggestions! That's outside my comfort zone so I'm not sure what to try.

I tried both solutions:
https://github.com/epfl-lara/stainless/compare/master...jad-hamza:fix-764 and
https://github.com/epfl-lara/stainless/compare/master...jad-hamza:fix2-764

There is the same error message ("Unknown call") on `fix-764`, and on `fix2-764` there is a crash with the cast on:
https://github.com/epfl-lara/stainless/blob/0b28e1e05af4b522425cee0d6ce6d0ee2e385b47/core/src/main/scala/stainless/extraction/methods/MethodLifting.scala#L74

```
[ Debug  ] java.lang.ClassCastException: inox.ast.Types$TypeParameter cannot be cast to stainless.extraction.oo.Trees$ClassType
[ Debug  ]      at stainless.extraction.methods.MethodLifting$BaseTransformer.transform(MethodLifting.scala:74)
[ Debug  ]      at stainless.extraction.methods.MethodLifting$transformer$1$.transform(MethodLifting.scala:209)
[ Debug  ]      at stainless.extraction.methods.MethodLifting.makeFunction(MethodLifting.scala:287)
[ Debug  ]      at stainless.extraction.methods.MethodLifting.transformMethod$1(MethodLifting.scala:98)
[ Debug  ]      at stainless.extraction.methods.MethodLifting.$anonfun$extract$5(MethodLifting.scala:104)
[ Debug  ]      at stainless.extraction.utils.ConcurrentCache.cached(ConcurrentCaches.scala:18)
[ Debug  ]      at stainless.extraction.ExtractionCaches$ExtractionCache.cached(ExtractionCaches.scala:165)
[ Debug  ]      at stainless.extraction.methods.MethodLifting.$anonfun$extract$4(MethodLifting.scala:104)
[ Debug  ]      at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
[ Debug  ]      at scala.collection.immutable.List.foreach(List.scala:392)
[ Debug  ]      at scala.collection.TraversableLike.map(TraversableLike.scala:238)
[ Debug  ]      at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
[ Debug  ]      at scala.collection.immutable.List.map(List.scala:298)
[ Debug  ]      at stainless.extraction.methods.MethodLifting.$anonfun$extract$3(MethodLifting.scala:103)
[ Debug  ]      at scala.collection.Iterator.foreach(Iterator.scala:941)
[ Debug  ]      at scala.collection.Iterator.foreach$(Iterator.scala:941)
[ Debug  ]      at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
[ Debug  ]      at scala.collection.MapLike$DefaultValuesIterable.foreach(MapLike.scala:213)
[ Debug  ]      at stainless.extraction.methods.MethodLifting.extract(MethodLifting.scala:93)
[ Debug  ]      at stainless.extraction.methods.MethodLifting.extract$(MethodLifting.scala:83)
[ Debug  ]      at stainless.extraction.methods.MethodLifting$$anon$1.extract(MethodLifting.scala:329)
[ Debug  ]      at stainless.extraction.methods.MethodLifting$$anon$1.extract(MethodLifting.scala:329)
[ Debug  ]      at stainless.extraction.utils.DebugPipeline.$anonfun$extract$2(DebugPipeline.scala:118)
[ Debug  ]      at scala.util.Try$.apply(Try.scala:213)
[ Debug  ]      at inox.utils.TimerStorage.runAndGetTime(Timer.scala:93)
[ Debug  ]      at inox.utils.TimerStorage.run(Timer.scala:88)
[ Debug  ]      at stainless.extraction.utils.DebugPipeline.$anonfun$extract$1(DebugPipeline.scala:118)
[ Debug  ]      at stainless.extraction.utils.DebugSymbols.debug(DebugPipeline.scala:64)
[ Debug  ]      at stainless.extraction.utils.DebugSymbols.debug$(DebugPipeline.scala:54)
[ Debug  ]      at stainless.extraction.utils.DebugPipeline$$anon$1.debug(DebugPipeline.scala:126)
[ Debug  ]      at stainless.extraction.utils.DebugPipeline.extract(DebugPipeline.scala:119)
[ Debug  ]      at stainless.extraction.utils.DebugPipeline.extract$(DebugPipeline.scala:117)
[ Debug  ]      at stainless.extraction.utils.DebugPipeline$$anon$1.extract(DebugPipeline.scala:126)
[ Debug  ]      at stainless.extraction.ExtractionPipeline$$anon$1.extract(ExtractionPipeline.scala:28)
[ Debug  ]      at stainless.extraction.ExtractionPipeline$$anon$1.extract(ExtractionPipeline.scala:28)
[ Debug  ]      at stainless.extraction.ExtractionPipeline$$anon$1.extract(ExtractionPipeline.scala:28)
[ Debug  ]      at stainless.extraction.ExtractionPipeline$$anon$1.extract(ExtractionPipeline.scala:28)
[ Debug  ]      at stainless.extraction.ExtractionPipeline$$anon$1.extract(ExtractionPipeline.scala:28)
[ Debug  ]      at stainless.extraction.ExtractionPipeline$$anon$1.extract(ExtractionPipeline.scala:28)
[ Debug  ]      at stainless.extraction.ExtractionPipeline$$anon$1.extract(ExtractionPipeline.scala:28)
[ Debug  ]      at stainless.extraction.ExtractionPipeline$$anon$1.extract(ExtractionPipeline.scala:28)
[ Debug  ]      at stainless.extraction.ExtractionPipeline$$anon$1.extract(ExtractionPipeline.scala:28)
[ Debug  ]      at stainless.extraction.ExtractionPipeline$$anon$1.extract(ExtractionPipeline.scala:28)
[ Debug  ]      at stainless.extraction.ExtractionPipeline$$anon$1.extract(ExtractionPipeline.scala:28)
[ Debug  ]      at stainless.extraction.ExtractionPipeline$$anon$1.extract(ExtractionPipeline.scala:28)
[ Debug  ]      at stainless.extraction.ExtractionPipeline$$anon$1.extract(ExtractionPipeline.scala:28)
[ Debug  ]      at stainless.extraction.ExtractionPipeline$$anon$1.extract(ExtractionPipeline.scala:28)
[ Debug  ]      at stainless.extraction.ExtractionPipeline$$anon$1.extract(ExtractionPipeline.scala:28)
[ Debug  ]      at stainless.ComponentRun.extract(Component.scala:75)
[ Debug  ]      at stainless.ComponentRun.extract$(Component.scala:75)
[ Debug  ]      at stainless.verification.VerificationRun.extract(VerificationComponent.scala:49)
[ Debug  ]      at stainless.ComponentRun.apply(Component.scala:98)
[ Debug  ]      at stainless.ComponentRun.apply$(Component.scala:97)
[ Debug  ]      at stainless.verification.VerificationRun.apply(VerificationComponent.scala:49)
[ Debug  ]      at stainless.ComponentRun.apply(Component.scala:112)
[ Debug  ]      at stainless.ComponentRun.apply$(Component.scala:111)
[ Debug  ]      at stainless.verification.VerificationRun.apply(VerificationComponent.scala:49)
[ Debug  ]      at stainless.frontend.SplitCallBack.$anonfun$processFunctionSymbols$2(SplitCallBack.scala:181)
[ Debug  ]      at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
[ Debug  ]      at scala.collection.immutable.List.foreach(List.scala:392)
[ Debug  ]      at scala.collection.TraversableLike.map(TraversableLike.scala:238)
[ Debug  ]      at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
[ Debug  ]      at scala.collection.immutable.List.map(List.scala:298)
[ Debug  ]      at stainless.frontend.SplitCallBack.processFunctionSymbols(SplitCallBack.scala:180)
[ Debug  ]      at stainless.frontend.SplitCallBack.processFunction(SplitCallBack.scala:154)
[ Debug  ]      at stainless.frontend.SplitCallBack.$anonfun$processSymbols$3(SplitCallBack.scala:138)
[ Debug  ]      at stainless.frontend.SplitCallBack.$anonfun$processSymbols$3$adapted(SplitCallBack.scala:137)
[ Debug  ]      at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:877)
[ Debug  ]      at scala.collection.Iterator.foreach(Iterator.scala:941)
[ Debug  ]      at scala.collection.Iterator.foreach$(Iterator.scala:941)
[ Debug  ]      at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
[ Debug  ]      at scala.collection.MapLike$DefaultKeySet.foreach(MapLike.scala:181)
[ Debug  ]      at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:876)
[ Debug  ]      at stainless.frontend.SplitCallBack.processSymbols(SplitCallBack.scala:137)
[ Debug  ]      at stainless.frontend.SplitCallBack.endExtractions(SplitCallBack.scala:67)
[ Debug  ]      at stainless.frontend.ThreadedFrontend$$anon$1.run(ThreadedFrontend.scala:38)
[ Debug  ]      at java.lang.Thread.run(Thread.java:748)
```
