### ISSUE TITLE
stainless-dotty crashes with NoSuchMethodError

### ISSUE THREAD

**Issue by jad-hamza** [epfl-lara/stainless#793]
I have this issue when I start `stainless-dotty` in the command-line (issue disappears with `--batched` option):

```
$ stainless-dotty --debug=frontend
[ Error  ] Stainless terminated with an error.
[ Error  ] Debug output is available in the file `stainless-stack-trace.txt`, you may report your issue on https://github.com/epfl-lara/stainless/issues
[ Debug  ] java.lang.NoSuchMethodError: scala.reflect.internal.util.package$.SomeOfNil()Lscala/Option;
[ Debug  ]      at scala.reflect.internal.Definitions$DefinitionsClass.$anonfun$newT1NoParamsMethod$1(Definitions.scala:1377)
[ Debug  ]      at scala.reflect.internal.Definitions$DefinitionsClass.newPolyMethod(Definitions.scala:1363)
[ Debug  ]      at scala.reflect.internal.Definitions$DefinitionsClass.newT1NoParamsMethod(Definitions.scala:1377)
[ Debug  ]      at scala.reflect.internal.Definitions$DefinitionsClass.Object_isInstanceOf$lzycompute(Definitions.scala:1123)
[ Debug  ]      at scala.reflect.internal.Definitions$DefinitionsClass.Object_isInstanceOf(Definitions.scala:1123)
[ Debug  ]      at scala.reflect.internal.Definitions$DefinitionsClass.syntheticCoreMethods$lzycompute(Definitions.scala:1412)
[ Debug  ]      at scala.reflect.internal.Definitions$DefinitionsClass.syntheticCoreMethods(Definitions.scala:1396)
[ Debug  ]      at scala.reflect.internal.Definitions$DefinitionsClass.symbolsNotPresentInBytecode$lzycompute(Definitions.scala:1426)
[ Debug  ]      at scala.reflect.internal.Definitions$DefinitionsClass.symbolsNotPresentInBytecode(Definitions.scala:1426)
[ Debug  ]      at scala.reflect.internal.Definitions$DefinitionsClass.init(Definitions.scala:1482)
[ Debug  ]      at scala.reflect.runtime.JavaUniverse.init(JavaUniverse.scala:154)
[ Debug  ]      at scala.reflect.runtime.JavaUniverse.<init>(JavaUniverse.scala:93)
[ Debug  ]      at scala.reflect.runtime.package$.universe$lzycompute(package.scala:29)
[ Debug  ]      at scala.reflect.runtime.package$.universe(package.scala:29)
[ Debug  ]      at inox.utils.InoxSerializer$ClassSerializer.<init>(Serialization.scala:235)
[ Debug  ]      at inox.utils.InoxSerializer.classSerializer(Serialization.scala:293)
[ Debug  ]      at inox.utils.InoxSerializer.classSerializers(Serialization.scala:533)
[ Debug  ]      at stainless.utils.StainlessSerializer.classSerializers(Serialization.scala:27)
[ Debug  ]      at stainless.utils.XLangSerializer.classSerializers(Serialization.scala:102)
[ Debug  ]      at inox.utils.InoxSerializer.<init>(Serialization.scala:519)
[ Debug  ]      at stainless.utils.StainlessSerializer.<init>(Serialization.scala:16)
[ Debug  ]      at stainless.utils.XLangSerializer.<init>(Serialization.scala:91)
[ Debug  ]      at stainless.utils.Serializer$.apply(Serialization.scala:199)
[ Debug  ]      at stainless.frontend.SplitCallBack.<init>(SplitCallBack.scala:117)
[ Debug  ]      at stainless.frontend.package$.getCallBack(package.scala:68)
[ Debug  ]      at stainless.frontend.package$.build(package.scala:35)
[ Debug  ]      at stainless.MainHelpers.newCompiler$1(MainHelpers.scala:166)
[ Debug  ]      at stainless.MainHelpers.main(MainHelpers.scala:167)
[ Debug  ]      at stainless.MainHelpers.main$(MainHelpers.scala:144)
[ Debug  ]      at stainless.Main$.main(Main.scala:3)
[ Debug  ]      at stainless.Main.main(Main.scala)
```

**Comment by jad-hamza** [comment]
This was caused by this commit https://github.com/epfl-lara/stainless/commit/35b054f11a21e89e83ae28511646b15bcb21c8db, I'm not sure why. Reverting it for now.
