### ISSUE TITLE
GenC crashes without intermediateVal

### ISSUE THREAD

**Issue by deiruch** [epfl-lara/stainless#908]
```scala
import stainless.lang._
import stainless.annotation._
import stainless.lang.StaticChecks.Ensuring
import scala.language.postfixOps

object Test3
{
	def abs(x: Int):Option[Int]=
	{
		if(x<0) Some(-x) else Some(x)
	}

	@export
	def example(x: Int):Int=
	{
		val unappliedFunction = abs _;
		
		//this works!
		val intermediateVal = unappliedFunction(x)
		intermediateVal match
		{
			case Some(v) => v
		}

		//this doesn't?
		unappliedFunction(x) match
		{
			case Some(v) => v
		}
	}
}
```

The above source results in a GenC crash when compiled. I would expect the second inline call to work as well. If that's not possible, I'd hope for a prettier error message - maybe with a line number? :)

```
inox.package$FatalError: scrutinee = unappliedFunction(x) of type class inox.ast.Expressions$Application is not supported by GenC
	at inox.Reporter.onFatal(Reporter.scala:42)
	at inox.Reporter.fatalError(Reporter.scala:53)
	at inox.Reporter.fatalError(Reporter.scala:113)
	at stainless.genc.phases.S2IRImpl.scrutRec$1(Scala2IRPhase.scala:315)
	at stainless.genc.phases.S2IRImpl.convertPatMap(Scala2IRPhase.scala:318)
	at stainless.genc.phases.S2IRImpl.rec(Scala2IRPhase.scala:792)
	at stainless.genc.phases.S2IRImpl.$anonfun$rec$18(Scala2IRPhase.scala:609)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.collection.TraversableLike.map(TraversableLike.scala:238)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
	at scala.collection.immutable.List.map(List.scala:298)
	at stainless.genc.phases.S2IRImpl.rec(Scala2IRPhase.scala:609)
	at stainless.genc.phases.S2IRImpl.buildLet(Scala2IRPhase.scala:133)
	at stainless.genc.phases.S2IRImpl.rec(Scala2IRPhase.scala:614)
	at stainless.genc.phases.S2IRImpl.buildLet(Scala2IRPhase.scala:133)
	at stainless.genc.phases.S2IRImpl.rec(Scala2IRPhase.scala:614)
	at stainless.genc.phases.S2IRImpl.$anonfun$rec$1(Scala2IRPhase.scala:496)
	at scala.Option.getOrElse(Option.scala:189)
	at stainless.genc.phases.S2IRImpl.rec(Scala2IRPhase.scala:435)
	at stainless.genc.phases.S2IRImpl.$anonfun$run$2(Scala2IRPhase.scala:69)
	at scala.collection.immutable.HashSet$HashSet1.foreach(HashSet.scala:321)
	at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:977)
	at stainless.genc.phases.S2IRImpl.run(Scala2IRPhase.scala:66)
	at stainless.genc.phases.Scala2IRPhase$.run(Scala2IRPhase.scala:40)
	at stainless.genc.phases.Scala2IRPhase$.run(Scala2IRPhase.scala:27)
	at stainless.genc.NamedLeonPhase.$anonfun$run$5(LeonPhase.scala:17)
	at scala.util.Try$.apply(Try.scala:213)
	at inox.utils.TimerStorage.runAndGetTime(Timer.scala:93)
	at inox.utils.TimerStorage.run(Timer.scala:88)
	at stainless.genc.NamedLeonPhase.run(LeonPhase.scala:17)
	at stainless.genc.NamedLeonPhase.run$(LeonPhase.scala:11)
	at stainless.genc.NamedLeonPhase$$anon$1.run(LeonPhase.scala:29)
	at stainless.genc.LeonPipeline$$anon$1.run(LeonPipeline.scala:12)
	at stainless.genc.LeonPipeline$$anon$1.run(LeonPipeline.scala:12)
	at stainless.genc.LeonPipeline$$anon$1.run(LeonPipeline.scala:12)
	at stainless.genc.LeonPipeline$$anon$1.run(LeonPipeline.scala:12)
	at stainless.genc.LeonPipeline$$anon$1.run(LeonPipeline.scala:12)
	at stainless.genc.LeonPipeline$$anon$1.run(LeonPipeline.scala:12)
	at stainless.genc.GenerateCPhase$.run(GenerateCPhase.scala:28)
	at stainless.genc.GenCRun.apply(GenCComponent.scala:80)
	at stainless.frontend.BatchedCallBack.$anonfun$endExtractions$15(BatchedCallBack.scala:106)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.collection.TraversableLike.map(TraversableLike.scala:238)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
	at scala.collection.immutable.List.map(List.scala:298)
	at stainless.frontend.BatchedCallBack.endExtractions(BatchedCallBack.scala:104)
	at stainless.frontend.ThreadedFrontend$$anon$1.run(ThreadedFrontend.scala:39)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by jad-hamza** [comment]
Should be fixed by https://github.com/epfl-lara/stainless/pull/910, thanks for the report!
