### ISSUE TITLE
Badly translated nested conditions in the AntiAliasing phase

### ISSUE THREAD

**Issue by brunnerant** [epfl-lara/stainless#916]
Nested conditions and assignments are incorrectly tracked by the `AntiAliasing` phase, resulting in an incorrect translation. The following example illustrates the bug:
```Scala
object Bug { 
  case class A(var a: BigInt)

  def bug(b1: Boolean, b2: Boolean) = {
      val a = A(1)
      val b = A(2)
      val c = A(3)
      val x = if (b1) (if (b2) a else b) else c
      x.a = 4
  }
}
```
This snippet is translated to (after `AntiAliasing`):
```Scala
def bug((b1: Boolean) @pure, (b2: Boolean) @pure): Unit = {
  var a: A = A(1)
  var b: A = A(2)
  var c: A = A(3)
  val x: A = if (b1) {
    if (b2) {
      a
    } else {
      b
    }
  } else {
    c
  }
  a = @unchecked (if (b1) {
    A(4)
  } else {
    a
  }).asInstanceOf[A]
  c = @unchecked (if (¬b1) {
    A(4)
  } else {
    c
  }).asInstanceOf[A]
  b = @unchecked (if (b1) {
    A(4)
  } else {
    b
  }).asInstanceOf[A]
  ()
}
```
As can be seen, the branching on the boolean `b2` is not part of the translated code, which is obviously wrong.

**Comment by vkuncak** [comment]
I am now getting 
```
java.lang.ClassCastException: inox.ast.Expressions$IfExpr cannot be cast to inox.ast.Expressions$Variable
	at stainless.extraction.imperative.TreeDeconstructor.$anonfun$deconstruct$6(Trees.scala:337)
	at inox.ast.Deconstructors$Operator$.$anonfun$unapply$1(Deconstructors.scala:569)
	at stainless.extraction.imperative.AntiAliasing$transformer$1$.transform(AntiAliasing.scala:533)
	at stainless.extraction.imperative.AntiAliasing$transformer$1$.$anonfun$transform$26(AntiAliasing.scala:454)```
