### ISSUE TITLE
Typing error with Nothing type and Generics

### ISSUE THREAD

**Issue by yannbolliger** [epfl-lara/stainless#945]
The following Scala program uses the `Nothing` type to throw an error without knowing the exact required type.

```scala
import stainless._
import stainless.lang._

object PatternReturn {
  sealed abstract class List[T]
  case class Nil[T]() extends List[T]
  case class Cons[T](_0: T, _1: List[T]) extends List[T]


  def first[T](self: List[T]): T = self match {
    case Cons(v, _) => v
    case _ => error[Nothing]("Empty list")
  }
}
```

We ran the program with `stainless ../../Panic.scala --vc-cache=no --type-checker=false`.
but it fails, with the following internal error:

```
[info] [Internal] Error: Type error: self match {
[info] [Internal]   case Cons(v, _) =>ckageBin 0s
[info] [Internal]     v
[info] [Internal]   case _ =>
[info] [Internal]     error[{ x: Object | @unchecked false }]("Empty list")
[info] [Internal] }, expected T, 
[info] [Internal] found <untyped>
[info] [Internal] 
[info] [Internal] Typing explanation:
[info] [Internal] self match {
[info] [Internal]   case Cons(v, _) =>
[info] [Internal]     v
[info] [Internal]   case _ =>
[info] [Internal]     error[{ x: Object | @unchecked false }]("Empty list")
[info] [Internal] } is of type <untyped>
[info] [Internal]   self is of type List[T]
[info] [Internal]   v is of type T
[info] [Internal]   error[{ x: Object | @unchecked false }]("Empty list") is of type Object. Trace:
[info] [Internal] - inox.ast.TypeOps$TypeErrorException$.apply(TypeOps.scala:29)
[info] [Internal] - inox.ast.TypeOps.typeCheck(TypeOps.scala:89)
...
```

<details>
<summary>entire stack trace</summary>

```
[info] [Internal] Error: Type error: self match {
[info] [Internal]   case Cons(v, _) =>ckageBin 0s
[info] [Internal]     v
[info] [Internal]   case _ =>
[info] [Internal]     error[{ x: Object | @unchecked false }]("Empty list")
[info] [Internal] }, expected T, 
[info] [Internal] found <untyped>
[info] [Internal] 
[info] [Internal] Typing explanation:
[info] [Internal] self match {
[info] [Internal]   case Cons(v, _) =>
[info] [Internal]     v
[info] [Internal]   case _ =>
[info] [Internal]     error[{ x: Object | @unchecked false }]("Empty list")
[info] [Internal] } is of type <untyped>
[info] [Internal]   self is of type List[T]
[info] [Internal]   v is of type T
[info] [Internal]   error[{ x: Object | @unchecked false }]("Empty list") is of type Object. Trace:
[info] [Internal] - inox.ast.TypeOps$TypeErrorException$.apply(TypeOps.scala:29)
[info] [Internal] - inox.ast.TypeOps.typeCheck(TypeOps.scala:89)
[info] [Internal] - inox.ast.TypeOps.typeCheck$(TypeOps.scala:85)
[info] [Internal] - inox.ast.SimpleSymbols$SimpleSymbols.typeCheck(SimpleSymbols.scala:12)
[info] [Internal] - inox.ast.Definitions$AbstractSymbols.ensureWellFormedFunction(Definitions.scala:228)
[info] [Internal] - inox.ast.Definitions$AbstractSymbols.ensureWellFormedFunction$(Definitions.scala:227)
[info] [Internal] - inox.ast.SimpleSymbols$SimpleSymbols.ensureWellFormedFunction(SimpleSymbols.scala:12)
[info] [Internal] - inox.ast.Definitions$AbstractSymbols.$anonfun$ensureWellFormedSymbols$2(Definitions.scala:223)
[info] [Internal] - inox.ast.Definitions$AbstractSymbols.$anonfun$ensureWellFormedSymbols$2$adapted(Definitions.scala:223)
[info] [Internal] - scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:985)
[info] [Internal] - scala.collection.immutable.Map$Map4.foreach(Map.scala:492)
[info] [Internal] - scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:984)
[info] [Internal] - inox.ast.Definitions$AbstractSymbols.ensureWellFormedSymbols(Definitions.scala:223)
[info] [Internal] - inox.ast.Definitions$AbstractSymbols.ensureWellFormedSymbols$(Definitions.scala:222)
[info] [Internal] - inox.ast.SimpleSymbols$SimpleSymbols.ensureWellFormedSymbols(SimpleSymbols.scala:12)
[info] [Internal] - inox.ast.Definitions$AbstractSymbols.$anonfun$inox$ast$Definitions$AbstractSymbols$$_tryWF$2(Definitions.scala:220)
[info] [Internal] - scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[info] [Internal] - scala.util.Try$.apply(Try.scala:213)
[info] [Internal] - inox.ast.Definitions$AbstractSymbols.$anonfun$inox$ast$Definitions$AbstractSymbols$$_tryWF$1(Definitions.scala:220)
[info] [Internal] - inox.utils.Lazy.get(Lazy.scala:13)
[info] [Internal] - inox.ast.Definitions$AbstractSymbols.ensureWellFormed(Definitions.scala:219)
[info] [Internal] - inox.ast.Definitions$AbstractSymbols.ensureWellFormed$(Definitions.scala:219)
[info] [Internal] - inox.ast.SimpleSymbols$SimpleSymbols.ensureWellFormed(SimpleSymbols.scala:12)
[info] [Internal] - inox.solvers.unrolling.AbstractUnrollingSolver.$anonfun$assertCnstr$2(UnrollingSolver.scala:167)
[info] [Internal] - scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[info] [Internal] - scala.util.Try$.apply(Try.scala:213)
[info] [Internal] - inox.utils.TimerStorage.runAndGetTime(Timer.scala:93)
[info] [Internal] - inox.utils.TimerStorage.run(Timer.scala:88)
[info] [Internal] - inox.solvers.unrolling.AbstractUnrollingSolver.$anonfun$assertCnstr$1(UnrollingSolver.scala:166)
[info] [Internal] - scala.util.Try$.apply(Try.scala:213)
[info] [Internal] - inox.utils.TimerStorage.runAndGetTime(Timer.scala:93)
[info] [Internal] - inox.utils.TimerStorage.run(Timer.scala:88)
[info] [Internal] - inox.solvers.unrolling.AbstractUnrollingSolver.assertCnstr(UnrollingSolver.scala:165)
[info] [Internal] - inox.solvers.unrolling.AbstractUnrollingSolver.assertCnstr$(UnrollingSolver.scala:165)
[info] [Internal] - inox.solvers.SolverFactory$$anon$12.assertCnstr(SolverFactory.scala:291)
[info] [Internal] - inox.solvers.SolverFactory$$anon$12.assertCnstr(SolverFactory.scala:291)
[info] [Internal] - stainless.verification.VerificationChecker.$anonfun$checkVC$2(VerificationChecker.scala:232)
[info] [Internal] - scala.util.Try$.apply(Try.scala:213)
[info] [Internal] - inox.utils.TimerStorage.runAndGetTime(Timer.scala:93)
[info] [Internal] - stainless.verification.VerificationChecker.checkVC(VerificationChecker.scala:228)
[info] [Internal] - stainless.verification.VerificationChecker.checkVC$(VerificationChecker.scala:214)
[info] [Internal] - stainless.verification.VerificationChecker$Checker$1.checkVC(VerificationChecker.scala:336)
[info] [Internal] - stainless.verification.VerificationChecker.$anonfun$checkVCs$2(VerificationChecker.scala:107)
[info] [Internal] - scala.concurrent.Future$.$anonfun$traverse$1(Future.scala:850)
[info] [Internal] - scala.collection.TraversableOnce$folder$1.apply(TraversableOnce.scala:196)
[info] [Internal] - scala.collection.TraversableOnce$folder$1.apply(TraversableOnce.scala:194)
[info] [Internal] - scala.collection.Iterator.foreach(Iterator.scala:943)
[info] [Internal] - scala.collection.Iterator.foreach$(Iterator.scala:943)
[info] [Internal] - scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
[info] [Internal] - scala.collection.IterableLike.foreach(IterableLike.scala:74)
[info] [Internal] - scala.collection.IterableLike.foreach$(IterableLike.scala:73)
[info] [Internal] - scala.collection.AbstractIterable.foreach(Iterable.scala:56)
[info] [Internal] - scala.collection.TraversableOnce.foldLeft(TraversableOnce.scala:199)
[info] [Internal] - scala.collection.TraversableOnce.foldLeft$(TraversableOnce.scala:192)
[info] [Internal] - scala.collection.AbstractTraversable.foldLeft(Traversable.scala:108)
[info] [Internal] - scala.concurrent.Future$.traverse(Future.scala:850)
[info] [Internal] - stainless.verification.VerificationChecker.checkVCs(VerificationChecker.scala:97)
[info] [Internal] - stainless.verification.VerificationChecker.checkVCs$(VerificationChecker.scala:90)
[info] [Internal] - stainless.verification.VerificationChecker$Checker$1.checkVCs(VerificationChecker.scala:336)
[info] [Internal] - stainless.verification.VerificationChecker.verify(VerificationChecker.scala:81)
[info] [Internal] - stainless.verification.VerificationChecker.verify$(VerificationChecker.scala:77)
[info] [Internal] - stainless.verification.VerificationChecker$Checker$1.verify(VerificationChecker.scala:336)
[info] [Internal] - stainless.verification.VerificationChecker$.verify(VerificationChecker.scala:350)
[info] [Internal] - stainless.verification.VerificationRun.execute(VerificationComponent.scala:128)
[info] [Internal] - stainless.verification.VerificationRun.execute(VerificationComponent.scala:53)
[info] [Internal] - stainless.ComponentRun.apply(Component.scala:106)
[info] [Internal] - stainless.ComponentRun.apply$(Component.scala:97)
[info] [Internal] - stainless.verification.VerificationRun.apply(VerificationComponent.scala:53)
[info] [Internal] - stainless.frontend.SplitCallBack.$anonfun$processFunctionsSymbols$2(SplitCallBack.scala:192)
[info] [Internal] - scala.collection.immutable.List.map(List.scala:293)
[info] [Internal] - stainless.frontend.SplitCallBack.processFunctionsSymbols(SplitCallBack.scala:191)
[info] [Internal] - stainless.frontend.SplitCallBack.$anonfun$processFunctions$5(SplitCallBack.scala:166)
[info] [Internal] - stainless.extraction.utils.ConcurrentCache.getOrElseUpdate(ConcurrentCaches.scala:15)
[info] [Internal] - stainless.frontend.SplitCallBack.processFunctions(SplitCallBack.scala:166)
[info] [Internal] - stainless.frontend.SplitCallBack.$anonfun$processSymbols$4(SplitCallBack.scala:151)
[info] [Internal] - stainless.frontend.SplitCallBack.$anonfun$processSymbols$4$adapted(SplitCallBack.scala:150)
[info] [Internal] - scala.collection.immutable.HashMap$HashMapKeys.$anonfun$foreach$1(HashMap.scala:150)
[info] [Internal] - scala.collection.immutable.HashMap$HashMap1.foreachEntry(HashMap.scala:400)
[info] [Internal] - scala.collection.immutable.HashMap$HashTrieMap.foreachEntry(HashMap.scala:732)
[info] [Internal] - scala.collection.immutable.HashMap$HashTrieMap.foreachEntry(HashMap.scala:732)
[info] [Internal] - scala.collection.immutable.HashMap$HashMapKeys.foreach(HashMap.scala:150)
[info] [Internal] - stainless.frontend.SplitCallBack.processSymbols(SplitCallBack.scala:150)
[info] [Internal] - stainless.frontend.SplitCallBack.endExtractions(SplitCallBack.scala:72)
[info] [Internal] - stainless.frontend.ThreadedFrontend$$anon$1.run(ThreadedFrontend.scala:39)
[info] [Internal] - java.lang.Thread.run(Thread.java:748)
```

</details>

Running the snippet _with_ the type checker also fails:
`stainless ../../Panic.scala --vc-cache=no`

```
[info] [ Fatal  ] ../../Panic.scala:12:15: Could not check that Object is a subtype of T
[info]                case _ => error[Nothing]("Empty list")
[info]                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[info] [ Error  ] Stainless terminated with an error.
[info] [ Error  ] Debug output is available in the file `stainless-stack-trace.txt`, you may report your issue on https://github.com/epfl-lara/stainless/issues
[info] [ Error  ] You may use --debug=stack to have the stack trace displayed in the output.
```

<details>
<summary>stack trace</summary>

```
[info] [ Debug  ] inox.package$FatalError: Could not check that Object is a subtype of T
[info] [ Debug  ] 	at inox.Reporter.onFatal(Reporter.scala:42)
[info] [ Debug  ] 	at inox.Reporter.fatalError(Reporter.scala:53)
[info] [ Debug  ] 	at stainless.verification.TypeChecker.isSubtype(TypeChecker.scala:1200)
[info] [ Debug  ] 	at stainless.verification.TypeChecker.isSubtype$(TypeChecker.scala:1114)
[info] [ Debug  ] 	at stainless.verification.TypeChecker$$anon$2.isSubtype(TypeChecker.scala:1452)
[info] [ Debug  ] 	at stainless.verification.TypeChecker.isSubtype(TypeChecker.scala:1153)
[info] [ Debug  ] 	at stainless.verification.TypeChecker.isSubtype$(TypeChecker.scala:1114)
[info] [ Debug  ] 	at stainless.verification.TypeChecker$$anon$2.isSubtype(TypeChecker.scala:1452)
[info] [ Debug  ] 	at stainless.verification.TypeChecker.checkType(TypeChecker.scala:1105)
[info] [ Debug  ] 	at stainless.verification.TypeChecker.checkType$(TypeChecker.scala:1012)
[info] [ Debug  ] 	at stainless.verification.TypeChecker$$anon$2.checkType(TypeChecker.scala:1452)
[info] [ Debug  ] 	at stainless.verification.TypeChecker.checkType(TypeChecker.scala:1094)
[info] [ Debug  ] 	at stainless.verification.TypeChecker.checkType$(TypeChecker.scala:1012)
[info] [ Debug  ] 	at stainless.verification.TypeChecker$$anon$2.checkType(TypeChecker.scala:1452)
[info] [ Debug  ] 	at stainless.verification.TypeChecker.checkType(TypeChecker.scala:1085)
[info] [ Debug  ] 	at stainless.verification.TypeChecker.checkType$(TypeChecker.scala:1012)
[info] [ Debug  ] 	at stainless.verification.TypeChecker$$anon$2.checkType(TypeChecker.scala:1452)
[info] [ Debug  ] 	at stainless.verification.TypeChecker.$anonfun$checkType$40(TypeChecker.scala:1336)
[info] [ Debug  ] 	at scala.Option.fold(Option.scala:251)
[info] [ Debug  ] 	at stainless.verification.TypeChecker.$anonfun$checkType$39(TypeChecker.scala:1336)
[info] [ Debug  ] 	at scala.Option.fold(Option.scala:251)
[info] [ Debug  ] 	at stainless.verification.TypeChecker.checkType(TypeChecker.scala:1335)
[info] [ Debug  ] 	at stainless.verification.TypeChecker.checkType$(TypeChecker.scala:1251)
[info] [ Debug  ] 	at stainless.verification.TypeChecker$$anon$2.checkType(TypeChecker.scala:1452)
[info] [ Debug  ] 	at stainless.verification.TypeChecker.$anonfun$checkType$42(TypeChecker.scala:1349)
[info] [ Debug  ] 	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
[info] [ Debug  ] 	at scala.collection.Iterator.foreach(Iterator.scala:943)
[info] [ Debug  ] 	at scala.collection.Iterator.foreach$(Iterator.scala:943)
[info] [ Debug  ] 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
[info] [ Debug  ] 	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
[info] [ Debug  ] 	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
[info] [ Debug  ] 	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
[info] [ Debug  ] 	at scala.collection.TraversableLike.map(TraversableLike.scala:286)
[info] [ Debug  ] 	at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
[info] [ Debug  ] 	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
[info] [ Debug  ] 	at stainless.verification.TypeChecker.checkType(TypeChecker.scala:1349)
[info] [ Debug  ] 	at stainless.verification.TypeChecker.checkType$(TypeChecker.scala:1348)
[info] [ Debug  ] 	at stainless.verification.TypeChecker$$anon$2.checkType(TypeChecker.scala:1452)
[info] [ Debug  ] 	at stainless.verification.TypeChecker.checkFunctionsAndADTs(TypeChecker.scala:1446)
[info] [ Debug  ] 	at stainless.verification.TypeChecker.checkFunctionsAndADTs$(TypeChecker.scala:1445)
[info] [ Debug  ] 	at stainless.verification.TypeChecker$$anon$2.checkFunctionsAndADTs(TypeChecker.scala:1452)
[info] [ Debug  ] 	at stainless.verification.VerificationRun.$anonfun$execute$3(VerificationComponent.scala:117)
[info] [ Debug  ] 	at scala.util.Try$.apply(Try.scala:213)
[info] [ Debug  ] 	at inox.utils.TimerStorage.runAndGetTime(Timer.scala:93)
[info] [ Debug  ] 	at inox.utils.TimerStorage.run(Timer.scala:88)
[info] [ Debug  ] 	at stainless.verification.VerificationRun.execute(VerificationComponent.scala:117)
[info] [ Debug  ] 	at stainless.verification.VerificationRun.execute(VerificationComponent.scala:53)
[info] [ Debug  ] 	at stainless.ComponentRun.apply(Component.scala:106)
[info] [ Debug  ] 	at stainless.ComponentRun.apply$(Component.scala:97)
[info] [ Debug  ] 	at stainless.verification.VerificationRun.apply(VerificationComponent.scala:53)
[info] [ Debug  ] 	at stainless.frontend.SplitCallBack.$anonfun$processFunctionsSymbols$2(SplitCallBack.scala:192)
[info] [ Debug  ] 	at scala.collection.immutable.List.map(List.scala:293)
[info] [ Debug  ] 	at stainless.frontend.SplitCallBack.processFunctionsSymbols(SplitCallBack.scala:191)
[info] [ Debug  ] 	at stainless.frontend.SplitCallBack.$anonfun$processFunctions$5(SplitCallBack.scala:166)
[info] [ Debug  ] 	at stainless.extraction.utils.ConcurrentCache.getOrElseUpdate(ConcurrentCaches.scala:15)
[info] [ Debug  ] 	at stainless.frontend.SplitCallBack.processFunctions(SplitCallBack.scala:166)
[info] [ Debug  ] 	at stainless.frontend.SplitCallBack.$anonfun$processSymbols$4(SplitCallBack.scala:151)
[info] [ Debug  ] 	at stainless.frontend.SplitCallBack.$anonfun$processSymbols$4$adapted(SplitCallBack.scala:150)
[info] [ Debug  ] 	at scala.collection.immutable.HashMap$HashMapKeys.$anonfun$foreach$1(HashMap.scala:150)
[info] [ Debug  ] 	at scala.collection.immutable.HashMap$HashMap1.foreachEntry(HashMap.scala:400)
[info] [ Debug  ] 	at scala.collection.immutable.HashMap$HashTrieMap.foreachEntry(HashMap.scala:732)
[info] [ Debug  ] 	at scala.collection.immutable.HashMap$HashTrieMap.foreachEntry(HashMap.scala:732)
[info] [ Debug  ] 	at scala.collection.immutable.HashMap$HashMapKeys.foreach(HashMap.scala:150)
[info] [ Debug  ] 	at stainless.frontend.SplitCallBack.processSymbols(SplitCallBack.scala:150)
[info] [ Debug  ] 	at stainless.frontend.SplitCallBack.endExtractions(SplitCallBack.scala:72)
[info] [ Debug  ] 	at stainless.frontend.ThreadedFrontend$$anon$1.run(ThreadedFrontend.scala:39)
[info] [ Debug  ] 	at java.lang.Thread.run(Thread.java:748)
```

</details>

**Comment by jad-hamza** [comment]
Can you try with `--debug=trees` to see if the type error happens after a particular phase?

**Comment by samarion** [comment]
It's probably due to a corner case in type encoding where the lub between an "object" type (`Nothing`) and a normal type (`T`) is a normal type itself, so encoding doesn't trigger.

Maybe it can be fixed by adding a special case in the `convert` function that transforms expected `Nothing` type into an error tree. Somewhere in this match expression:
https://github.com/epfl-lara/stainless/blob/43aa5c786ca5b969e442e8078b1c38fa3dae3a41/core/src/main/scala/stainless/extraction/oo/TypeEncoding.scala#L161

**Comment by yannbolliger** [comment]
> Can you try with `--debug=trees` to see if the type error happens after a particular phase?

Yes, it happens after TypeEncoding: `Ensuring well-formedness after phase TypeEncoding...`.

**Comment by yannbolliger** [comment]
> @samarion: Maybe it can be fixed by adding a special case in the `convert` function that transforms expected `Nothing` type into an error tree. Somewhere in this match expression:

The triple of the pattern match is  ` (error[{ x: Object | @unchecked false }]("Empty list"), Nothing, T)`, so the expected type is T, couldn't the error be transformed to `error[T]`?

**Comment by samarion** [comment]
Yes, but I'm not sure we can handle the general case by pushing down the expected type. We could also have a non-terminating function which returns `Nothing`... That's  why I mentioned just replacing the `Nothing` tree with `error[Type]`, but we can also be smart about it and attempt pushing the type down and only replace by `error` if it fails.

**Comment by romac** [comment]
@samarion Isn't the issue basically that

```scala
def bar: Nothing = ???
def foo[T]: T = bar
```

is transformed as

```scala
def bar: { x: Object | false } = ???
def foo(T: Object => Boolean): { x: Object | T(x) } = bar
```

instead of

```scala
def bar: { x: Object | false } = ???
def foo(T: Object => Boolean): { x: Object | T(x) } = bar
```

?

(disclaimer: haven't tested it, but that seems like a minimized version of what's happening in the report above, maybe @yannbolliger can tell us more)

Is there not way to handle this in this case?

**Comment by samarion** [comment]
Uh, I assume the first transformed code block should have been
```scala
def bar: { x: Object | false } = ???
def foo[T]: T = bar
```
Yes, that's one way to view the issue. Erasing `T` to a type predicate would indeed solve the issue, but it would need a non-trivial change in the way we discover type parameters which need erasing.

Also, erasing type parameters into type predicates makes downstream verification harder. I feel like we could avoid the extra cost by replacing expressions with type `Nothing` by `error[expectedType]` when the actual type is `Nothing` but `!isObject(expectedType)`. This should be a safe change since `Nothing` is not inhabited. The only drawback of this approach is that we lose the `Nothing`-typed expression in the source.

**Comment by yannbolliger** [comment]
I'll try to solve that special case first:

> ... replacing expressions with type `Nothing` by `error[expectedType]` when the actual type is `Nothing` but `!isObject(expectedType)`.

**Comment by yannbolliger** [comment]
> we lose the Nothing-typed expression in the source.
Does that mean we lose its effects?

**Comment by samarion** [comment]
> Does that mean we lose its effects?

Yes, but evaluating a `Nothing`-typed expression should anyway either crash or result in non-termination, so I'm not sure it's an issue?
