### ISSUE TITLE
error G559F8DE6: Operator >> is not supported by GenC

### ISSUE THREAD

**Issue by deiruch** [epfl-lara/stainless#986]
```scala
	@export
	def write16u(_v:UInt16):Unit =
	{
		val test = (_v >> 8)
		//val test = (_v.widen[UInt32].toSigned[Int32].toInt >> 8) same issue
	}
```

this code results in the following error when using GenC

```
error G559F8DE6: Operator >> is not supported by GenC
                             val test = (_v >> 8)
                                         ^^^^^^^
```

Changing the code to
```scala
	@export
	def write16u(_v:UInt16):Unit =
	{
		val test = (_v.toInt >> 8)
		//val test = (_v.widen[UInt32].toInt >> 8) same issue
	}
```
hits an assertion in GenC:
```
java.lang.AssertionError: assertion failed
	at scala.Predef$.assert(Predef.scala:208)
	at stainless.genc.phases.IR2CImpl.rec(IR2CPhase.scala:194)
	at stainless.genc.phases.IR2CImpl.rec(IR2CPhase.scala:213)
	at stainless.genc.phases.IR2CImpl.rec(IR2CPhase.scala:258)
	at stainless.genc.phases.IR2CImpl.rec(IR2CPhase.scala:85)
	at stainless.genc.phases.IR2CImpl.$anonfun$rec$3(IR2CPhase.scala:78)
	at scala.collection.mutable.HashMap.getOrElseUpdate(HashMap.scala:86)
	at stainless.genc.phases.IR2CImpl.stainless$genc$phases$IR2CImpl$$rec(IR2CPhase.scala:74)
	at stainless.genc.phases.IR2CImpl.$anonfun$rec$1(IR2CPhase.scala:64)
	at stainless.genc.phases.IR2CImpl.$anonfun$rec$1$adapted(IR2CPhase.scala:64)
	at scala.collection.immutable.Stream.foreach(Stream.scala:533)
	at stainless.genc.phases.IR2CImpl.rec(IR2CPhase.scala:64)
	at stainless.genc.phases.IR2CImpl.apply(IR2CPhase.scala:33)
	at stainless.genc.phases.IR2CPhase$.run(IR2CPhase.scala:24)
	at stainless.genc.phases.IR2CPhase$.run(IR2CPhase.scala:18)
	at stainless.genc.NamedLeonPhase.$anonfun$run$5(LeonPhase.scala:17)
	at scala.util.Try$.apply(Try.scala:213)
	at inox.utils.TimerStorage.runAndGetTime(Timer.scala:93)
	at inox.utils.TimerStorage.run(Timer.scala:88)
	at stainless.genc.NamedLeonPhase.run(LeonPhase.scala:17)
	at stainless.genc.NamedLeonPhase.run$(LeonPhase.scala:11)
	at stainless.genc.NamedLeonPhase$$anon$1.run(LeonPhase.scala:29)
	at stainless.genc.LeonPipeline$$anon$1.run(LeonPipeline.scala:12)
	at stainless.genc.LeonPipeline$$anon$1.run(LeonPipeline.scala:12)
	at stainless.genc.GenerateCPhase$.run(GenerateCPhase.scala:28)
	at stainless.genc.GenCRun.apply(GenCComponent.scala:89)
	at stainless.frontend.BatchedCallBack.$anonfun$endExtractions$3(BatchedCallBack.scala:104)
	at scala.collection.immutable.List.map(List.scala:293)
	at stainless.frontend.BatchedCallBack.endExtractions(BatchedCallBack.scala:102)
	at stainless.frontend.ThreadedFrontend$$anon$1.run(ThreadedFrontend.scala:39)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by jad-hamza** [comment]
Thanks for the report, it should be fixed now in https://github.com/epfl-lara/stainless/pull/988
It should work now with `>>>` (this corresponds to `bvlshr` in SMT lib)
Not sure what we should do with `>>` (`bvashr`)?

**Comment by deiruch** [comment]
Thanks for the fix!
